couchbase/couchbase-cxx-client

CMakeLists.txt
cmake/Testing.cmake
couchbase/io/http_command.hxx
test/test_helper.hxx

Motivation
==========
The diagnostics ping test is segfaulting.
Modification
============
Simply guarded against calling into it if null.   We can follow up later
and decide how to deal with it generally (like, use a noop_meter).
While there, fixed up some issues with building this inside another
project - CMAKE_SOURCE_DIR is the _outer_ source directory, so migrated
to PROJECT_SOURCE_DIR throughout.
Also a small issue with the test helpers.  Now, we can pass in the server version.  However,
I believe we may have an issue specifying DP, will follow up later on that.
Results
=======
passing tests.

CXXCBC-5 Handle no meter in http requests

---

couchbase/io/mcbp_session.hxx

The issue was found by thread sanitizer.

Fix data race in MCBP session

---

test/test_helper_native.hxx
test/test_native_binary_operations.cxx
test/test_native_durability.cxx
test/test_native_management.cxx
test/test_native_trivial_crud.cxx
test/test_native_trivial_query.cxx

To reduce verbosity in the simplest cases, the cluster class implements
shortcuts that are waiting for completion internally

add synchronous versions of open, close and open_bucket

---

couchbase/errors.hxx
couchbase/io/mcbp_session.hxx
couchbase/protocol/cmd_get_error_map.hxx
couchbase/protocol/cmd_mutate_in.hxx
couchbase/protocol/status.hxx
couchbase/topology/error_map.hxx
couchbase/topology/error_map_json.hxx

* sync protocol errors with current server implementation
* update doc strings for attributes using server docs
* add new rate-limit attribute
C++ SDK does not enforce strict check for unknown attributes as libcouchbase does, so no need extra work there

CXXCBC-18: support ErrorMap v2

---

test/test_helper.hxx
test/test_native_durability.cxx
test/test_native_trivial_query.cxx

- Skip durability tests on version < 6.5.
- We only need to open a bucket for query tests if the server doesn't support gcccp.

Fix tests running against older server versions

---

test/test_integration_management.cxx
test/utils/CMakeLists.txt
test/utils/wait_until.cxx
test/utils/wait_until.hxx

Add test helpers that wait for an arbitrary condition
Add test helper that waits for a bucket to become healthy

Fix flaky bucket management test

---

couchbase/topology/configuration.hxx

gcc 11 complains that `<optional>` is not included yet in `configuration.hxx`

add missing header

---

couchbase/errors.hxx
couchbase/io/mcbp_session.hxx
couchbase/operations/document_query.cxx
test/test_unit_utils.cxx

1. RFC has these codes specified, so it would be better if we use them,
because our errors are basically numeric values.
2. Output operator for std::error_code uses bare integer value instead
of message, and it will be easier to search for codes in the sources.

explicitly assign values to errors

---

test/test_integration_collections.cxx
test/test_integration_trivial_query.cxx
test/utils/wait_until.cxx
test/utils/wait_until.hxx

The collection manifest can be partially propagated in a multi node cluster. Until all nodes can be checked, add a sleep after create/drop

SDKQE-2495: Temporarily add sleep after scope and collection changes

---

couchbase/protocol/client_request.cxx
couchbase/protocol/client_request.hxx
test/CMakeLists.txt
test/test_integration_crud.cxx

When the value was compressed, the body length and datatype fields were
not updated because of non-reference argument. The patch improves API a
bit, and modification of the packet done by the caller now.

fix snappy compression of the value

---

test/utils/server_version.cxx
test/utils/server_version.hxx

Cluster version appends -edition. Account for this and parse it so we can test community edition
Fix neo version to apply to all future versions

Fix live cluster version parse

---

couchbase/document_id.cxx

Used to be 30, but now it is 251.

CXXCBC-60: Collection and Scope Name have 251 character limit

---

test/utils/integration_test_guard.cxx
test/utils/test_context.cxx
test/utils/test_context.hxx

Allow passing in a certificate and key path for cert auth testing

SDKQE-2432: Support for Multiple Root Certs testing

---

test/test_integration_management.cxx

Wait until a bucket is healthy on all nodes before using it to prevent timeouts during delete caused by MB-48059.

SDKQE-2522: Reduce bucket management test time on older server versions

---

test/test_integration_management.cxx
test/utils/server_version.hxx

Running on 5.5 causes the analytics tests to fail when using tls. Analytics was dev preview in 5.5 so it's fine to skip it

SDKQE-2529: Don't run analytics tests on 5.5

---

couchbase/protocol/client_response.hxx

Unknown status codes will be handled using error map

CXXCBC-124: remove status code validity assertion from protocol parser

---

couchbase/logger/configuration.hxx
couchbase/logger/logger.cxx

Motivation
==========
When the client is used in the sdk wrappers (python, node, etc...), it
would be nice to allow the logging to be forwarded to the wrapper's
logging handlers.
Modification
============
Simplest thing to do is add a spdlog::sinks::sink to the logger
configuration.  If it is set, we add it.   Then the wrappers can
implement a sink that does the handoff.
Results
=======
I didn't add tests, as there are no logging tests anyways.  I did for
the transactions logging, and I've used this in python.

CXXCBC-54 Add log forwarding

---

couchbase/io/http_session.hxx

We fixed this for mcbp_session in #151. Do the same for http_session

CXXCBC-134: Close http_session before conecting to next endpoint

---

cmake/OpenSSL.cmake

To disable this behaviour, use option
COUCHBASE_CXX_CLIENT_USE_HOMEBREW_TO_DETECT_OPENSSL=FALSE

try to detect OpenSSL using homebrew on MacOS

---

couchbase/tracing/threshold_logging_tracer.cxx

reporter is using microseconds to report outliers, but we store duration
with millisecond resolution, which basicaly zeroes last three digits

Increase resolution of threshold tracer up to microseconds

---

test/utils/server_version.hxx

The analytics service was introduced in 6.0 so there are likely bugs that are causing test failures. The failures do not occur on any later version so it is safe to disable this

SDKQE-2716: Skip analytics tests in 6.0

---

core/cluster_options.hxx
test/tools/tool_kv_loader.cxx

In order to optimize freeze/thaw cycle clustermap notification should be
disabled. Otherwise the SDK will be required to process all stale
notifications after thaw.

CXXCBC-203: disable clustermap nofication by default

---

core/logger/logger.cxx
core/logger/logger.hxx
test/utils/logger.cxx

the default pattern does not include file location info to reduce
verbosity, but the tests enable it for easier debugging.

record line, file, and function names into log message

---

core/protocol/frame_info_utils.cxx

When more then one framing extras is being used, the boundaries
calcualted incorrectly (old size is not taken into account), which leads
to write attempts beyond vector's buffer, and leads to memory
corruption.

fix framing boundaries calculation in case of multiple frames

---

core/io/http_session.hxx
test/test_integration_query.cxx

it is not necessary to keep lock while executing HTTP handler

CXXCBC-174: reduce scope of the http request lock

---

couchbase/collection.hxx
test/test_integration_transcoders.cxx

The error context were up-casted to base class which does not have subdoc-specific fields (like index of the first error)

return subdocument error context from future-based subdoc methods

---

test/benchmark_integration_get.cxx
test/test_helper.hxx
test/test_integration_analytics.cxx
test/test_integration_arithmetic.cxx
test/test_integration_binary_operations.cxx
test/test_integration_collections.cxx
test/test_integration_connect.cxx
test/test_integration_crud.cxx
test/test_integration_diagnostics.cxx
test/test_integration_durability.cxx
test/test_integration_management.cxx
test/test_integration_query.cxx
test/test_integration_read_replica.cxx
test/test_integration_subdoc.cxx
test/test_integration_tracer.cxx
test/test_integration_transcoders.cxx
test/test_unit_json_streaming_lexer.cxx

Before:
```
REQUIRE_FALSE(!(ctx.ec()))
with expansion:
!couchbase.key_value:113
```
After:
```
REQUIRE_FALSE(!(ctx.ec()))
with expansion:
!couchbase.key_value:113
with message:
path_not_found (113)
```

improve readability of the error_code assertions

---

CMakeLists.txt
core/cluster_options.cxx
core/cluster_options.hxx
core/config_profile.cxx
core/config_profile.hxx
test/CMakeLists.txt
test/test_unit_config_profiles.cxx

Motivation
==========
Allow users can apply a named profile, rather than set several configuration options when making a cluster.
Modification
============
Added a config_profile class, which applies some changes to a
cluster_options object which is passed in.   Then created a
development_profile which applies some specific options.
Added a config_profiles class, accessed via a singleton static call (known_profiles) which allows a user to add new config_profile derived classes to the known_profiles.
Results
=======
Added unit tests, which all pass.

CXXCBC-221: Support for configuration profiles

---

core/utils/movable_function.hxx
test/test_unit_utils.cxx

Right now we just delegate move assignment and constructor to std::function, which does not clean the source, which in turn lets "operator bool()" return true after the function has been moved.

CXXCBC-226: ensure that moving from movable_function will clear the source

---

CMakeLists.txt
core/bucket.hxx
core/cluster.hxx
core/cluster_options.hxx
core/config_listener.hxx
core/impl/bootstrap_state_listener.hxx
core/impl/dns_srv_tracker.cxx
core/impl/dns_srv_tracker.hxx
core/io/CMakeLists.txt
core/io/dns_client.hxx
core/io/dns_codec.hxx
core/io/dns_config.cxx
core/io/dns_config.hxx
core/io/http_session_manager.hxx
core/io/mcbp_session.hxx
core/topology/configuration.cxx
core/topology/configuration.hxx
test/tools/tool_kv_loader.cxx
test/utils/integration_test_guard.cxx
test/utils/test_context.cxx
test/utils/test_context.hxx

When DNS SRV records are used to connect to the SDK it's possible for the underlying addresses to change, i.e. the cluster to move. We need to detect this happening and react accordingly so that the SDK can continue to work correctly.

CXXCBC-172: refresh DNS SRV when cluster uncontactable

---

core/operations/document_mutate_in.cxx
core/protocol/status.cxx

The server can return either NOT_STORED or EXISTS error when inserting an existing document (MB-50742).

CXXCBC-246: convert not_store code to document_exists

---

core/cluster.hxx
core/meta/version.cxx

When the user has not set any root ca provider but is using TLS then we should trust both the system store and the Capella root CA.

CXXCBC-235: load system CAs when the trust certificate is not provided

---

core/impl/common_error_category.cxx

Authentication failure can occur due to trying to authenticate against a hibernated bucket, this should be communicated in the error message

CXXCBC-234: error message for bucket hibernation

---

CMakeLists.txt
core/impl/transaction_error_category.cxx
core/impl/transaction_op_error_category.cxx
core/transactions.hxx
core/transactions/attempt_context_impl.cxx
core/transactions/attempt_context_impl.hxx
core/transactions/exceptions.cxx
core/transactions/exceptions.hxx
core/transactions/internal/exceptions_internal.hxx
core/transactions/internal/transaction_context.hxx
core/transactions/transaction_context.cxx
core/transactions/transaction_get_result.hxx
core/transactions/transactions.cxx
couchbase/error_codes.hxx
couchbase/transaction_error_context.hxx
couchbase/transaction_op_error_context.hxx
couchbase/transactions.hxx
couchbase/transactions/async_attempt_context.hxx
couchbase/transactions/attempt_context.hxx
couchbase/transactions/transaction_get_result.hxx
test/CMakeLists.txt
test/test_transaction_transaction_public_async_api.cxx
test/test_transaction_transaction_public_blocking_api.cxx

Initial exposure of public api for transactions.   Will need to add transaction configs when we have a public api for creating the cluster (so there can be a transactions_config, etc...).   Also need queries exposed - felt they needed public query api first, but I'll look again, to be sure.

CXXCBC-243 and CXXCBC-244: Expose kv transactions as public api

---

test/test_transaction_transaction_public_async_api.cxx
test/test_transaction_transaction_public_blocking_api.cxx
test/test_transaction_transaction_simple.cxx
test/test_transaction_transaction_simple_async.cxx

Since adding <memory> header didn't seem to help on Jenkins, we don't really need to do it.   A reinterpret_cast to a reference is fine, since we are just calling a method and not saving that pointer anyways.

Move away from reinterpret_pointer_cast<> for mac build issue

---

core/io/mcbp_parser.cxx

The library incorrectly calculates offset of the body when alternative response layout is being used (when flexible extra frames presented).
For regular get operations it is not visible, but get_replica responses contain key, and wrong offset cause snappy uncompress function to give up, and the application receives compressed payload. Which cannot be parsed as JSON.

CXXCBC-251: fix snappy decompression for get_replica

---

couchbase/query_options.hxx

The setter seems to have had a cut/paste issue.   Simple fix.

CXXCBC-253 query_options not setting scope_qualifier

---

core/transactions/attempt_context_impl.hxx
couchbase/cluster_options.hxx
couchbase/transactions/async_attempt_context.hxx
couchbase/transactions/attempt_context.hxx
examples/game_server.cxx
test/test_transaction_transaction_public_async_api.cxx
test/test_transaction_transaction_public_blocking_api.cxx

Using public api.   While at it, noticed the public api is more
convenient to use with `collection&` (rather than `shared_ptr<collection>`), so I
changed that as well.

CXXCBC-254 Update txn example

---

examples/CMakeLists.txt
examples/async_game_server.cxx

Added async_game_server - follows the existing game_server, but the update of the player and removal of the monster are in parallel.

CXXCBC-256 Async transactions example

---

core/transactions/transaction_context.cxx

Here lets just lower the max retries for calls that use `retry_delay` to `50` from `100`.  That should (probably) allow jenkins testing to proceed without overflowing the stack.
There is another ticket (CXXCBC-263) to track the proper fix for this issue.  Here, we just want to get the fit tests running.

TXNCXX-268 Segfault in jenkins fit tests

---

core/transactions/transactions_cleanup.cxx

After the previous commit for this ticket, I noticed another complaint from ASAN.  Small fix to just copy variables into the retry lambda rather than capture by reference.  Generally, though, I notice sometimes the API takes a const reference and copies, other times it takes an
object and moves.   Ideally the txn api should be a bit more consistent
on that - will make a ticket for that as well.

TXNCXX-268 ASAN issue in fit tests

---

.github/workflows/tests.yml
bin/run-unit-tests
core/cluster.hxx
core/io/mcbp_session.cxx
test/test_integration_crud.cxx
test/test_integration_range_scan.cxx

with this option, we don't get chance to inspect coredump files in case of test failures

remove pipefail option from test shell script

---

core/impl/cluster.cxx
core/transactions/attempt_context_impl.cxx
couchbase/cluster.hxx

While there, lets see if blocking cluster.close until the transactions have finished stopping will help the crash at close seen on fit.

Check for expiry in begin work

---

core/impl/get_all_replicas.cxx

Do not propagate error if result set is not empty, but the last response has failed.

CXXCBC-271: fix get_all_replicas behaviour

---

core/collections_component.cxx
core/range_scan_orchestrator.cxx
couchbase/cluster.hxx

Since FIT uses the public api, we need (at least for now) a way to get the core cluster object from the public cluster object, to use kv range
scan.   Added an accessor for that, for now.
Also added a check to apply the limit on a sampling scan, so next() stops when the limit is reached.
And a small logging change so we can see the collection being refreshed.

CXXCBC-257 Support for FIT testing of kv range scan

---

core/impl/query.cxx
core/transactions/attempt_context_impl.cxx
core/transactions/attempt_context_impl.hxx
core/transactions/durability_level.hxx
couchbase/transactions/transaction_keyspace.hxx

Though some issues were fixed in previous commits, this addresses the remaining ones.  Now we will return the expected errors from kv operations done through query.
While there, corrected a typo in transactions durability levels, a small issue in transaction_keyspace.  Also, added an error_code to override
what build_transaction_query_result would otherwise decide upon.   This
will be useful as we transition away from exceptions in txn core.

CXXCBC-261 Query error handling issues

---

core/transactions/attempt_context_impl.cxx
core/transactions/transactions_cleanup.cxx
test/test_transaction_transaction_simple.cxx

The atrs and client-records had `"u0000"` as the body, instead of a single `0` byte.   Thus they would be indexed by the index service, and other problematic things.
Simple fix, and added a test to catch any regressions in the future.

TXNCXX-260 - ExtBinaryMetadata bug

---

core/transactions/attempt_context_impl.cxx
core/transactions/attempt_context_impl.hxx
core/transactions/exceptions.cxx
core/transactions/exceptions.hxx
core/transactions/forward_compat.hxx
core/transactions/transaction_context.cxx
test/test_transaction_transaction_context.cxx
test/test_transaction_transaction_public_blocking_api.cxx

Updates transactions to give an ignorable exception (in the core api) when a transactional insert discovers the document already exists (as long as it isn't in a transaction itself).  The public api just returns an error, and in either case that error doesn't stop the transaction.

CXXCBC-197: Add support for ExtInsertExisting

---

core/transactions.hxx
core/transactions/async_attempt_context.hxx
core/transactions/attempt_context_impl.cxx
core/transactions/attempt_context_impl.hxx
test/test_transaction_transaction_public_async_api.cxx
test/test_transaction_transaction_public_blocking_api.cxx
test/utils/transactions_env.h

That's inconvienent - since you have to perform a kv op on it before the transaction.  So - added a function to insure it is open, on the public api calls.
While there, noticed an issue with cache_error_async, where we move the callback yet use it in the function as well.  For now, not using movable_function, allowing a copy, until I rework that function.

CXXCBC-259 Transactions public api expects bucket already open

---

core/operations/document_query.cxx
core/operations/management/query_index_build.cxx
core/operations/management/query_index_create.cxx
core/operations/management/query_index_drop.cxx
core/operations/management/query_index_get_all.cxx
core/operations/management/query_index_get_all_deferred.cxx
test/test_integration_management.cxx

The decision we have made is to always send a `query_context`, and live with the errors we see from 6.x and earlier for the management calls.  We could follow up with an option that allowed to user to specify this isn't put in the calls, if really needed.

CXXCBC-275 Update query_context handling in query management calls

---

core/platform/uuid.cc

CXXCBC-205: perf, use thread-local UUID generator

---

core/io/http_session.hxx
core/io/mcbp_session.cxx
test/tools/tool_kv_loader.cxx

The writing procedure should be invoked from the IO thread and bound to IO executor. Otherwise when main thread invokes ASIO write directly, the OpenSSL structures are not guaranteed to be thread-safe.

CXXCBC-285: write to sockets from IO threads

---

core/io/mcbp_parser.cxx
core/io/mcbp_parser.hxx
core/utils/json.cxx

I found that in mcbp_session_impl::do_read, 39% of the time was in mcbp::parser::next, with the vast majority of that in the std::transform
call after uncompressing the data.   By using vector::insert instead,
that dropped to only 11% of the time in do:read.
Probably the upshot here is to look for everywhere we are filling containers with a back_inserter and considering a way to modify that to not loop and instead copy in blocks.
before: 
after:

Eliminate looping transform in mcbp_parser::next

---

.github/workflows/tests.yml
.github/workflows/windows.yml
bin/build-tests.rb

* set timeout to be safe, and not to waste to much time
* increase number of parallel jobs for cmake to 2 (works for now, but if it will be a problem, we can go back to 1)
* use Release build time as it consumes less space during build and less likely hit the disk limit on github actions.

set build timeouts for github actions

---

core/meta/version.cxx
core/meta/version.hxx

These functions could be useful in our performance framework to identify the library.

expose more functions to get version info

---

core/meta/features.hxx
core/meta/version.cxx
core/meta/version.hxx
test/test_unit_utils.cxx

also covers special case for tagged releases in sdk_semver() function

CXXCBC-290: add header with feature macros

---

core/logger/configuration.hxx
core/logger/level.hxx
core/logger/logger.hxx

The `logger.hxx` does not include `configuration.hxx`, because it is
often not needed (default logger is being used), but `configuration.hxx`
itself depends on the log level. So to workaround this dependency for
cases, where only `configuration.hxx` included, we extract logger level
into its own header file.

logger: extract level.hxx to reduce coupling

---

core/cluster.hxx
core/impl/cluster.cxx
core/meta/CMakeLists.txt
core/metrics/CMakeLists.txt
core/metrics/logging_meter.cxx
core/metrics/logging_meter.hxx
core/tracing/CMakeLists.txt
core/tracing/threshold_logging_tracer.cxx
core/tracing/threshold_logging_tracer.hxx
couchbase/metrics/meter.hxx
couchbase/tracing/request_tracer.hxx
examples/minimal.cxx
test/utils/wait_until.cxx

After this change, the library got issues with stopping cluster properly: https://github.com/couchbaselabs/couchbase-cxx-client/pull/359/files#diff-d57958cc60b900a216af3a607194ccac57e75457e69eddfa953cca5b33f2cc78R59.
So I dig it a bit and found several issues:
* meter uses raw pointer to capture itself in the periodic timer (which causes leak and potential use-after-free)
* we should really try to signal timers in tracer and meter before relying on destructors, because some references might be still hold by IO threads
* when error occurs during core::cluster::open(), we should ensure that the cluster in closed state, in particular meter/tracer should be also stopped.

fix tracer and meter ref-counting

---

core/transactions/attempt_context_impl.hxx

Found an issue with operations after commit/rollback, just missing the logic to create the expected cause for those failures.

CXXCBC-194 ExtThreadSafe followup

---

core/transactions/staged_mutation.cxx

When we stage an insert, and get an ambiguous fail back, we look for the
doc and examine it to see if we can retry, etc...   When doing so, if
the doc was staged successfully, we just need to make sure the that we
use the staged_mutation's content, not the content in the
staged_mutation's doc, as that will have the results of looking at the
document after we staged it as a tombstone, so the content will be
empty.   This showed up in some ambiguous fail tests in fit.  Simple
fix.

CXXCBC-310 Transaction fit test errors

---

core/transactions/attempt_context_impl.cxx
test/test_transaction_transaction_simple.cxx

When we have removed a doc in this transaction, and then call
get_optional, we expect to just get an empty optional.   However, the
handling was raising a transaction_operation_failed.  Simple fix - the
get_doc call can return no error, and no document.  When that happens
and we are in a get_optional, we should just return the empty optional.
While at it, added some simple `get` and `get_optional` tests that were missing.   And
added a test reproducing the issue Sergey saw.

CXXCBC-316: Core txn get_optional after query issue

---

core/transactions/attempt_context_impl.hxx
core/transactions/internal/transaction_context.hxx
core/transactions/transaction_context.cxx

While looking for issues, and running with TSAN, I noticed this race. Ultimately an obvious one, surprised I didn't see it till now.  We just needed to lock access to the {{attempts_}} in the {{transaction_context}}.

CXXCBC-310 Explore fit errors

---

cmake/ThirdPartyDependencies.cmake

It brings perfromance improvements.
More info at: https://github.com/google/snappy/compare/1.1.8...1.1.10

Update snappy from 1.1.8 to 1.1.10

---

core/transactions/active_transaction_record.hxx

The effect is that the expiry seems to be a very large positive number. Lets just read it as an int32_t, cap it at 0 on the low side.  Turns out we definitely cap at 0 when we write, so this probably has to be from some old version that had flawed logic when writing.

CXXCBC-320 Negative expiry in atr can result in 'stuck' docs.

---

core/meta/version.cxx

These symbols were renamed, but version.cxx was not updated accordingly.

fix macro symbols for build info

---

core/utils/connection_string.cxx
core/utils/connection_string.hxx
test/test_unit_connection_string.cxx

When an invalid connection string parameter (either invalid key or value) is encountered only a warning logging message is outputted. The caller (i.e. a wrapper SDK) cannot check for the existence of parsing issues to raise an appropriate exception if it wants.
* Added a `warnings` property (`std::vector<std::string>`) in the `connection_string` struct where all parsing warnings can be gathered.
* Any warning logging messages that were previously outputted as a result of parsing issues are now pushed to the `warnings` vector instead, giving the option to the caller to decide whether to output logging messages or raise an exception
* Added some warnings for some parsing issues that were not previously being recorded (Invalid boolean, IP protocol and TLS verification mode values)
* Added …

CXXCBC-326: Set connection_string warnings property when invalid connection string parameter is encountered

---

CMakeLists.txt
core/bucket.cxx
core/bucket.hxx
core/cluster.hxx
core/error_context/key_value.cxx
core/error_context/key_value.hxx
core/impl/key_value_error_context.cxx
core/impl/query_error_context.cxx
core/io/mcbp_command.hxx
core/io/mcbp_session.cxx
core/io/mcbp_session.hxx
core/protocol/client_response.hxx
couchbase/analytics_error_context.hxx
couchbase/error_context.hxx
couchbase/fmt/key_value_error_map_attribute.hxx
couchbase/key_value_error_context.hxx
couchbase/manager_error_context.hxx
couchbase/query_error_context.hxx
couchbase/subdocument_error_context.hxx
docs/cbc-get.md
docs/cbc-pillowfight.md
tools/get.cxx
tools/pillowfight.cxx

Instead of letting session restarting itself, only allow it to removed itself from the bucket. And in the end, just notify the bucket to check configuration and establish connections to the endpoints that don't have it yet.

CXXCBC-328: fix restarting MCBP sessions

---

bin/api.rb
bin/init-cluster
bin/load-sample-buckets
core/io/mcbp_session.cxx
core/topology/collections_manifest_fmt.hxx
test/test_integration_collections.cxx
test/test_integration_examples.cxx
test/test_integration_management.cxx
test/test_integration_query.cxx
test/test_integration_search.cxx
test/test_transaction_public_async_api.cxx
test/test_transaction_public_blocking_api.cxx
test/utils/server_version.hxx
test/utils/wait_until.cxx
test/utils/wait_until.hxx

it contains improved setup scripts, as well as some test stability improvements, 
* better waiting for collections to be propagated (still not perfect, but closer), 
* cleanup of the collections (it behaves worse when tests leave a lot of the scopes and collections)
* skipping travel-sample for Capella
* avoid using non-portable index options for FTS
* improved test case naming in transactions

CXXCBC-331: fix FTS index provisioning script and improve test stability

---

core/range_scan_orchestrator.cxx
core/scan_result.cxx
core/scan_result.hxx
test/test_integration_range_scan.cxx

Added `is_cancelled()` method which is useful for some wrappers (e.g. Python). Included a test to verify that it works correctly

Add `is_cancelled()` method to `scan_result`

---

core/range_scan_orchestrator.cxx
test/test_integration_range_scan.cxx

* `errc::common::invalid_argument` when concurrency is non-positive
* Some tidying up in the tests - created a `get_vbucket_map()` function to make the code less repetitive

Return invalid_argument error code when concurrency is not positive in range scan

---

core/range_scan_orchestrator.cxx
test/test_integration_range_scan.cxx

Currently the behaviour when this happens is undefined. Return range_scan_completed if the scan is cancelled to indicate that no more results are going to be returned. Wrappers use range_scan_completed as a signal to end the result iteration

Return range_scan_completed if more items are requested after scan cancellation

---

core/impl/query.cxx
core/operations/document_query.cxx
core/operations/document_query.hxx
core/topology/capabilities.hxx
core/topology/capabilities_fmt.hxx
core/topology/configuration.hxx
core/topology/configuration_json.hxx
couchbase/query_options.hxx
test/CMakeLists.txt
test/test_unit_query.cxx

* Added `use_replica` option for query in both core and public APIs as an optional boolean. If set, it is included in the query request body.
* Added `n1ql_read_from_replica` cluster capability which is checked when `use_replica` is set and a `feature_not_available` error code is returned if the capability is not present.

CXXCBC-340: Support query with read from replica

---

core/range_scan_orchestrator.cxx
test/test_integration_range_scan.cxx

When the scan is cancelled, close the item channels for all streams (not only the ones with `running` status). Fixes issue in wrappers (seen in Ruby) where the backend could not be destroyed if the scan was terminated before all streams had run (e.g. in sampling scans).

Close all item channels when scan is cancelled

---

core/topology/capabilities.hxx
core/topology/capabilities_fmt.hxx
core/topology/configuration.hxx
core/topology/configuration_json.hxx

Adding the ability to check whether range scan is supported so wrappers have the option of failing the operation before creating a range scan orchestrator

CXXCBC-348: Add range_scan bucket capability

---

.github/workflows/windows.yml
bin/build-tests.rb

I found what was the problem with openssl on windows at github actions was.  They updated agent which now has openssl preinstalled. And for some reason 'choco install openssl' there now install into that preinstalled directory (i believe that choco just delegates installation process to .exe installed, which in turn discovers previous installation and tries to update it), Anyway all we need to do is to stop using 'choco install' and update cmake command line to use new location.

use preinstalled OpenSSL for github actions windows agent

---

.gitignore
couchbase/get_and_lock_options.hxx
couchbase/get_and_touch_options.hxx
couchbase/get_options.hxx
couchbase/insert_options.hxx
couchbase/lookup_in_options.hxx
couchbase/mutate_in_options.hxx
couchbase/remove_options.hxx
couchbase/replace_options.hxx
couchbase/touch_options.hxx
couchbase/unlock_options.hxx
couchbase/upsert_options.hxx

when wrapper includes both core and public API classes, some names might be sensitive to the order of the headers. In order to workaround this problem, use fully qualified names for the classes in the public headers

use fully qualified names to avoid conflicts in wrappers

---

core/impl/lookup_in_any_replica.cxx
core/operations/document_lookup_in_any_replica.hxx
test/test_integration_subdoc.cxx

Changes: 
- Added a check to see if the spec count is above the maximum amount in core and public API for LookupInAnyReplica
- Added core and public API tests

CXXCBC-365: lookup_in_any_replica not returning invalid arguments with too many specs

---

core/impl/lookup_in.cxx
couchbase/lookup_in_result.hxx
test/test_integration_subdoc.cxx

When an error occurs for a specific spec, throw the appropriate exception. Previously any spec-specific error codes were ignored resulting in decoding failures instead

CXXCBC-366: Expose spec-specific errors in the public API for lookup in

---

core/impl/lookup_in_all_replicas.cxx
core/impl/lookup_in_any_replica.cxx
core/operations/document_lookup_in.cxx
core/operations/document_lookup_in_all_replicas.hxx
core/operations/document_lookup_in_any_replica.hxx
test/test_integration_subdoc.cxx

Changes:
- Subdoc exists spec doesn't return an error, per the RFC
- Fixed bug with public API lookupInReplica not setting per-entry error code

CXXCBC-119 Subdoc exists should return a true/false value rather than error

---

core/cluster.hxx
core/timeout_defaults.hxx

Changes to be consistent with the latest RFC updates:
* Reducing the default value for `idle_http_connection_timeout` from 4.5s to 1s
* Producing an info-level logging message when `idle_http_connection_timeout` is more than 4.5s

CXXCBC-359: Reduce default HTTP idle timeout

---

core/operations/management/collection_update.cxx

In `update_collection`, convert `collection with name ... not found` response to a `collection_not_found`  error code, similar to `bucket_not_found` and `scope_not_found`

Handle collection not found response in update_collection

---

core/operations/management/bucket_create.cxx
core/operations/management/bucket_update.cxx
test/test_integration_management.cxx

Changes:
- Add check for bucket already exists message in create_bucket

CXXCBC-374: create_bucket does not return a BucketExists error when a duplicate bucket is created

---

core/impl/lookup_in_all_replicas.cxx
core/impl/lookup_in_any_replica.cxx
core/impl/lookup_in_replica.cxx
core/operations/document_lookup_in.cxx
core/operations/document_lookup_in_all_replicas.hxx
core/operations/document_lookup_in_any_replica.hxx
test/test_integration_subdoc.cxx

Path not found errors were cleared in #444. In addition to that, the value of the spec result should be set to the JSON representation of the exists field if the result was success or path-not-found. Relevant section of the RFC:
> If the result came from an `exists` lookup, calls Exists to get a boolean, and uses the JSON representation of that boolean as the "value" in the next step. Propagates any exceptions thrown by `Exists`.
* Set value to the JSON encoding of the `exists` boolean for `exists` spec results
* Clear the `path_not_found` error in `lookup_in_replica_request::make_response`, to avoid having to duplicate the logic for `lookup_in_any_replica` and `lookup_in_all_replicas`. Remove the checks for a `path_not_found` error code everywhere that's no longer necessary because of …

CXXCBC-119: Set value of subdoc exists to "true" or "false" if result is success or path-not-found

---

core/impl/get_all_buckets.cxx
core/impl/get_bucket.cxx
core/management/bucket_settings.hxx
core/management/bucket_settings_json.hxx
core/operations/management/bucket_create.cxx
core/operations/management/bucket_update.cxx
couchbase/management/bucket_settings.hxx

Changes: 
- Change BucketSettings unrequired fields to be optional
- Update request encoding logic so the SDK doesn't send the fields unless they are specified

CXXCBC-376 Create and Update bucket sending unnecessary fields to server

---

core/io/http_command.hxx
core/io/mcbp_command.hxx
core/tracing/noop_tracer.hxx
couchbase/tracing/request_span.hxx

Profiling indicates that non-trivial time is spent assigning tags to spans, which is wasted effort if noop_tracer is being used.
Borrowing an optimisation from the JVM SDKs, where we skip this assignment in this case.
This optimisation, together with another small one that will be submitted separately, produced around a 15% performance improvement.
Downside: this does have to touch the public request_span API.

CXXCBC-387: Optimising tags for noop_tracer

---

core/io/mcbp_session.cxx

Profiling indicates that non-trivial time is spent in this logic, which is called on every request.
There appears to be no reason not to cache this formatting in the existing variables, as local_endpoint_address_ is only being used here.
When tested together with another optimisation, this resulted in around a 15% performance improvement.

CXXCBC-387: Cache formatted mbcp_session endpoints

---

core/meta/version.cxx
test/test_unit_utils.cxx

It is going to be always short but useful addition like "bssl/1010107f", which we can track on the server side to help debugging TLS-related issues.

Announce SSL library version in user agent string

---

cmake/0001-fix-build-for-mingw-w64-ucrt-x86_64-toolchain.patch
cmake/OpenSSL.cmake

Apple ARM should provide support for all three features below, otherwise BoringSSL will fail to compile:
* __ARM_NEON
* __ARM_FEATURE_AES
* __ARM_FEATURE_SHA2
https://github.com/google/boringssl/blob/ad57528d2c978543106f9b115bd0eb658f3ebdd2/crypto/cpu_aarch64_apple.c#L49-L54
It turns out, that at this time all three versions of gcc from homebrew (11, 12, 13) only expose `__ARM_NEON`
```
$ echo | g++-13 -dM -E -x c++ - | grep '__ARM_NEON\|__ARM_FEATURE_AES\|__ARM_FEATURE_SHA2'
#define __ARM_NEON 1
$ echo | g++-12 -dM -E -x c++ - | grep '__ARM_NEON\|__ARM_FEATURE_AES\|__ARM_FEATURE_SHA2'
#define __ARM_NEON 1
$ echo | g++-11 -dM -E -x c++ - | grep '__ARM_NEON\|__ARM_FEATURE_AES\|__ARM_FEATURE_SHA2'
#define __ARM_NEON 1
```
while system compiler which is Apple Clang, exposes all of them
```
$ …
```

Patch BoringSSL for Windows MinGW and detect Apple ARM

---

cmake/OpenSSL.cmake

we need further investigation of the issue with BoringSSL and gcc on ARM architectures for MacOS. For some reason, gcc that shipped by Homebrew cannot compile our BoringSSL

relax check for support on MacOS/aarch64

---

core/protocol/status.cxx
test/test_integration_crud.cxx

KV_LOCKED should be exposed as `cas_mismatch` only for the unlock operation. This makes it consistent with the behaviour of other SDKs and the expectation of the relevant FIT test.
From the retry handling RFC:
> Locked 0x09 (Reason: KV_LOCKED)
Note: do NOT retry on KV_LOCKED for the "Unlock" command (the retry handler should never see it in the first place! (Reason is that _**this needs to be surfaced as a cas mismatch exception to the user**_ and not being retried

CXXCBC-404: KV_LOCKED status should be exposed as cas_mismatch for unlock

---

core/bucket.cxx
core/io/mcbp_command.hxx
core/io/mcbp_session.cxx

Motivation
----------
Currently if a KV operation receives a NMVB, it is possible the operation will raise a request_canceled error. When the client receives a NMVB there are circumstances in which we should attempt to retry the operation instead of raising a request_canceled.
Changes
-------
Update logic for handling NMVB KV responses so that retries are possible when appropriate.

CXXCBC-403: Allow retries for KV not_my_vbucket response

---

core/bucket.cxx
core/cluster_options.hxx
core/io/mcbp_session.cxx
core/protocol/cmd_hello.hxx
core/protocol/hello_feature.hxx
core/protocol/hello_feature_fmt.hxx
core/topology/configuration.hxx
couchbase/behavior_options.hxx
tools/CMakeLists.txt
tools/beam.cxx
tools/beam.hxx
tools/cbc.cxx
tools/utils.cxx
tools/utils.hxx

Implement only deduplication flag from the RFC, and enable clustermap
change notifications. I this patch, we only want to use full
notifications, and do not turn off polling. So the SDK will be able to
receive new configuration sooner, but still be chatty as older versions.
Also this patch introduces tool cbc-beam that can send requests to specific vbucket or node id

CXXCBC-368: Subscribe to clustermap notifications to speedup failover

---

core/impl/key_value_error_category.cxx
core/meta/features.hxx
core/protocol/status.cxx
core/protocol/status.hxx
couchbase/error_codes.hxx
couchbase/fmt/key_value_status_code.hxx
couchbase/key_value_status_code.hxx
test/test_integration_crud.cxx
test/utils/server_version.hxx

* Support the `not_locked` (0x0e) KV status and map it to the `errc::key_value::document_not_locked` error code
* Added relevant tests

CXXCBC-412: Support document_not_locked

---

CMakeLists.txt
core/impl/analytics_index_manager.cxx
core/impl/cluster.cxx
couchbase/analytics_index_manager.hxx
couchbase/cluster.hxx
couchbase/connect_link_analytics_options.hxx
couchbase/create_dataset_analytics_options.hxx
couchbase/create_dataverse_analytics_options.hxx
couchbase/create_index_analytics_options.hxx
couchbase/create_link_analytics_options.hxx
couchbase/disconnect_link_analytics_options.hxx
couchbase/drop_dataset_analytics_options.hxx
couchbase/drop_dataverse_analytics_options.hxx
couchbase/drop_index_analytics_options.hxx
couchbase/drop_link_analytics_options.hxx
couchbase/get_all_datasets_analytics_options.hxx
couchbase/get_all_indexes_analytics_options.hxx
couchbase/get_links_analytics_options.hxx
couchbase/get_pending_mutations_analytics_options.hxx
couchbase/management/analytics_dataset.hxx
couchbase/management/analytics_index.hxx
couchbase/management/analytics_link.hxx
couchbase/replace_link_analytics_options.hxx
test/test_integration_management.cxx

* Add `analytics_index_manager` in the public API and all associated options classes
* Add `management::analytics_index`, `management::analytics_dataset` and `management::analytics_link` (with its three concrete implementations as per the RFC) in the public API
* Add relevant tests
* Fix the assertions for `get_pending_mutations` in the Core API test

CXXCBC-308: Add analytics index manager in the public API

---

core/impl/collection.cxx
couchbase/collection.hxx
couchbase/mutation_result.hxx
couchbase/touch_options.hxx

Changes: 
- Change return type of touch to mutation_result
- Add additional mutation_result constructor

CXXCBC-405 Return type for touch is 'result' instead of 'mutation_result'

---

core/operations/document_query.cxx
core/operations/management/error_utils.cxx
core/operations/management/query_index_create.cxx
core/operations/management/query_index_drop.cxx

* Handle `"Index does not exist"` query error
* Add handling for the 5000 error code in `document_query` (copied the one from the query management operations)
* Handle the possibility of `"status"` not being included in the query response - an example where this happens is with the query `drop index notfound on default;`
All query FIT tests pass

CXXCBC-409: Add handling for 'index does not exist' query error

---

core/impl/collection.cxx
couchbase/collection.hxx
couchbase/mutation_result.hxx
couchbase/touch_options.hxx

Reverts couchbaselabs/couchbase-cxx-client#493
The Touch operation does not return mutation token, so it is not really a Mutation.
I see that DCP has opcode for Expiration replication: https://github.com/couchbase/kv_engine/blob/master/docs/dcp/documentation/commands/expiration.md
Also @Matt-Woz said that protostellar returns MutationResult for Touch, should not we expect something special for GetAndTouch operation too?
@brett19, what do you think? Shall we revert this change?
The spec is not consistent, it mentions both IMutationResult and IResult at the same time:
https://github.com/couchbaselabs/sdk-rfcs/blob/c84c821cc738e1244d9c97f6a0e3f7814bd1f599/rfc/0053-sdk3-crud.md?plain=1#L719-L735

Revert "CXXCBC-405 Return type for touch is 'result' instead of 'mutation_result'"

---

CMakeLists.txt
core/impl/bucket.cxx
core/impl/cluster.cxx
core/impl/diagnostics.cxx
core/impl/diagnostics.hxx
couchbase/bucket.hxx
couchbase/cluster.hxx
couchbase/diagnostics_options.hxx
couchbase/diagnostics_result.hxx
couchbase/endpoint_diagnostics.hxx
couchbase/endpoint_ping_report.hxx
couchbase/ping_options.hxx
couchbase/ping_result.hxx
couchbase/service_type.hxx
test/CMakeLists.txt
test/test_integration_diagnostics.cxx
test/test_unit_diagnostics.cxx

The `ping` and `diagnostics` operations currently only exist in the Core API, they also need to be exposed in the Public API
* Add `ping()` to public `Cluster` and `Bucket` APIs
* Add `diagnostics() to the public `Cluster` API
* Add any relevant options & results to Public API (`diagnostics_options`, `ping_options`, `diagnostics_result`, `ping_result`, `endpoint_diagnostics`, `endpoint_ping_report`, `service_type`, `ping_state`, `endpoint_state`)
* Add tests (the public API equivalents of the existing core diagnostics tests)
* Moved the existing core diagnostics unit tests to a file separate from the integration tests
All tests pass

CXXCBC-401: Add ping & diagnostics to public API

---

couchbase/get_options.hxx
tools/get.cxx

When an excessive number of projections is set in the options, the projections are not set at all, but the SDK should fall back to a full-doc fetch and return a valid projected result.

CXXCBC-426 Get with very large projection test is returning fields outside of the projection

---

core/operations/management/collection_create.cxx
core/operations/management/collection_create.hxx
core/operations/management/collection_update.cxx
core/operations/management/collection_update.hxx
core/topology/collections_manifest.hxx
core/topology/collections_manifest_json.hxx
couchbase/create_collection_options.hxx
couchbase/management/collection_spec.hxx
couchbase/update_collection_options.hxx
test/test_integration_management.cxx
test/utils/server_version.hxx

The server has added support for the maxTTL value of -1 which is used to denote 'no expiry'
* Change the type of `max_expiry` in the collection management APIs (both core and public) from `uint32_t` to `int32_t` to allow setting it to -1. The server accepts values in the range [-1, 2,147,483,647] which can be represented by a 32-bit signed integer.
* Return `errc::invalid_argument` when a value less than -1 is provided
* Add tests for `create_collection` and `update_collection` with different values for `max_expiry`

CXXCBC-346: Support for maxTTL value of -1 for collection 'no expiry'

---

core/operations/management/collection_create.cxx
core/operations/management/collection_update.cxx
test/test_integration_management.cxx

The error message when the bucket does not support history retention has changed in newer server versions. Replace the error message checks for `feature_not_available` with a bucket capability check before sending the collection create/update request.

CXXCBC-431: Add check for history retention bucket capability in collection create/update

---

test/test_integration_diagnostics.cxx

The ping timeout test can sometimes fail because the KV ping returns before the 1 millisecond timeout. Set the timeout to 0 milliseconds to ensure that all pings time out

Change timeout in ping/diagnostics timeout tests from 1 to 0 milliseconds

---

core/bucket.cxx
core/io/mcbp_session.cxx
core/io/mcbp_session.hxx

Instead of letting each MCBP session to poll for configuration automatically, make bucket object responsible for the polling orchestration and iterate over the list of known session to use only one socket to fetch configuration.

CXXCBC-284: Use round-robin for config polling

---

core/cluster.cxx
core/operations/management/collection_create.cxx
core/operations/management/collection_update.cxx
test/test_integration_management.cxx

The `http_context` appears to be at the cluster level, so it wasn't clear which bucket's capabilities were being checked. This resulted in unpredictability, as seen in FIT and in the Python SDK's test suite.
Add a new `execute_with_bucket_capability` method that after ensuring that the bucket is open, it checks for the presence of the capability using `with_bucket_configuration` and then proceeds to do the operation if successful. This is now used for `create_collection` and `update_collection`.
Tests pass (including FIT)

CXXCBC-431: Fix history retention bucket capability check

---

core/operations/document_query.cxx

This was caught by a failing FIT test. Now checking the error message to return `feature_not_available` instead of `invalid_argument` when the server reports that it does not recognise the `preserve_expiry` parameter.

CXXCBC-421: Return `feature_not_available` when query preserve expiry is not supported

---

core/operations/document_search.cxx
test/test_integration_search.cxx

Changes:
- Return feature_not_available on a 404 response from FTS

Add feature_not_available handling to search

---

couchbase/codec/json_transcoder.hxx
couchbase/codec/raw_json_transcoder.hxx
couchbase/codec/raw_string_transcoder.hxx
test/test_integration_transcoders.cxx

* Add `raw_json_transcoder` and `raw_string_transcoder`
* Add tests for the new transcoders

CXXCBC-442: Add support for the raw_json and raw_string transcoders

---

core/cluster.cxx
core/io/mcbp_session.cxx
core/io/mcbp_session.hxx
core/origin.cxx
core/origin.hxx

Use hostnames from the cluster configuration to bootstrap bucket connections instead of original list from the connection string.
It is possible that connection string does not have any node that has KV service, and in this case the SDK will fail to open bucket.

CXXCBC-447: Use addresses from the config to bootstrap bucket

---

core/impl/query_index_manager.cxx
core/operations/management/query_index_create.cxx
core/operations/management/query_index_create.hxx
couchbase/collection_query_index_manager.hxx
couchbase/query_index_manager.hxx
test/CMakeLists.txt
test/test_integration_management.cxx
test/test_unit_management.cxx

Make the SDK consistent with the management RFC revision/clarification in couchbaselabs/sdk-rfcs#116
* Rename `fields` parameter to `keys` in the Public API's `create_index()`
* Encode each index key provided to `create_index()` by surrounding them with backticks
* Add unit test for the encoding & update integration test to reflect these changes

CXXCBC-191: Create Index Key Encoding

---

core/meta/features.hxx
core/transactions/internal/exceptions_internal.hxx

Required for FIT performer exception validation

Add to_raise getter to transaction_operation_failed

---

core/bucket.cxx
core/bucket.hxx
core/io/mcbp_command.hxx
core/protocol/status.cxx
core/protocol/status.hxx
couchbase/fmt/key_value_status_code.hxx
couchbase/key_value_status_code.hxx

On 0x0d (EConfigOnly) status code SDK will request new configuration, and send current operation to retry orchestrator.

CXXCBC-456: handle 0x0d (config_only) status from KV

---

core/cluster.cxx
core/impl/collection.cxx
core/io/http_session_manager.hxx
core/io/mcbp_session.cxx
core/operations/document_lookup_in_all_replicas.hxx
core/operations/document_lookup_in_any_replica.hxx
core/operations/document_query.cxx
core/operations/document_search.cxx
core/topology/capabilities.hxx
core/topology/capabilities_fmt.hxx
core/topology/configuration.hxx
core/topology/configuration_fmt.hxx
core/topology/configuration_json.hxx
test/test_unit_query.cxx

Fail fast if the cluster does not support new search features.
The patch also updates list of known capabilities and provides utilities to help with asserting their presence in more general way.

CXXCBC-452: detect new search capabilities

---

core/io/mcbp_session.cxx

We do not want any actions from old bootstrap handler once the session decided to re-bootstrap. For example, bucket could not be selected, but we might still get configuration responses before socket reset.

CXXCBC-450: reset bootstrap handler before re-bootstrap

---

docs/cbc-analytics.md
docs/cbc-get.md
docs/cbc-pillowfight.md
docs/cbc-query.md
docs/cbc.md
docs/cli.hxx
tools/CMakeLists.txt
tools/pillowfight.cxx

* record latencies and display histogram in the end of the run
* fix termination condition when using multiple threads
* use running average for runtime rate display
* allow to configure separate batch size for queries
* fixed links in the reference pages

Improvements in cbc-pillowfight

---

.gitignore
core/io/dns_client.cxx
core/io/dns_config.cxx
core/io/dns_config.hxx

Avoid assuming Google DNS and rather report DNS-SRV lookup failure. The details still logged and user still can specify their DNS server in options.

CXXCBC-336: Do not fallback to 8.8.8.8, if we cannot obtain system DNS server

---

core/impl/collection.cxx
core/operations/document_lookup_in_any_replica.hxx
test/test_integration_subdoc.cxx

Per the RFC, LookupInAnyReplica should only ever return DocumentIrretrievable & we shouldn't be enforcing the spec count on the client-side

CXXCBC-480 LookupInAnyReplica TooManySpecs Failures

---

core/meta/features.hxx
core/transactions/atr_cleanup_entry.cxx
core/transactions/attempt_context_impl.cxx
core/transactions/attempt_context_testing_hooks.cxx
core/transactions/attempt_context_testing_hooks.hxx
core/transactions/cleanup_testing_hooks.cxx
core/transactions/cleanup_testing_hooks.hxx
core/transactions/internal/utils.hxx
core/transactions/staged_mutation.cxx
core/transactions/staged_mutation.hxx
core/transactions/transactions_cleanup.cxx
core/transactions/utils.cxx

Transactions hooks are sometimes required to perform KV operations. They should be async to avoid blocking in IO threads that are calling the hooks.
Add a callback to all hooks so they can be executed asynchronously and called from callbacks of KV operations without blocking the IO thread.

CXXCBC-458: Transactions hooks should be asynchronous

---

core/io/mcbp_session.cxx

If doing a ping during a rebalance of a multi-node cluster it is possible that one or more of the nodes are in the process of completing bootstrap.  This can cause the ping operation to timeout.  Since we know when a node has bootstrapped or not, the SDK should not ping a node that has not bootstrapped.  This will allow for the ping operation to complete without the worry of a timeout due to waiting on the bootstrap process to successfully complete.
* Add a mechanism to keep track of the last error w/in the `bootstrap_handler`.
* If ping is called, check if the node has bootstrapped.  If the node is not bootstrapped, add the kv node to the ping report with an error indicating either the last error message from the `bootstrap_handler` or a generic message, but do not execute the ping …

CXXCBC-461: Do not send ping to nodes that have not completed bootstrap.

---

core/operations/document_search.cxx
core/operations/document_search.hxx
test/utils/wait_until.cxx

Motivation
==========
If scoring is disable on server versions > 7.6 the SDK can crash when parsing the hits in the result.  The SDK should be a bit more lenient when processing hits. Also instead of crashing, the SDK should raise an exception if there is a problem when parsing results.
Changes
=======
* Update JSON parsing of search results
* Added flags to output search request and/or response
* Updated search test suite

CXXCBC-481: Fix potential crash when parsing search result hits

---

core/range_scan_orchestrator_options.hxx

The retry strategy is unset instead of being set to best-effort by default.
This has been found via the custom transcoder FIT tests which create a collection and immediately perform a range scan on them, where the SDK fast-fails instead of retrying the get_collection_id operation (which uses the retry strategy specified in the orchestrator).

CXXCBC-482: Range scan orchestrator should use best effort retry strategy by default

---

core/impl/cluster.cxx
core/transactions.hxx
core/transactions/internal/transactions_cleanup.hxx
core/transactions/transactions.cxx
core/transactions/transactions_cleanup.cxx
couchbase/cluster.hxx
couchbase/fork_event.hxx
test/test_integration_examples.cxx

In order to gracefully survive fork() syscall, the library should be able to move itself into stable and predictable state. In particular ASIO should not have any pending work, and all IO thread should be stopped. After the fork() the parent process retains control over all file descriptors, but the child have to reconnect them (ASIO does it in its hooks), and also the SDK should restart all the IO workers.
At the moment, the only worker thread that the library controls is the one that in charge of the transactions cleanup, but later once the public API will hide ASIO context, it will become in charge of the restarting IO threads.
In case of the wrappers, that use core API directly, they must be able to stop all IO threads before fork(), wait for work completion, then perform the syscall …

CXXCBC-448: Expose hooks for fork() scenarious

---

core/cluster.cxx
core/origin.cxx
core/origin.hxx

bucket
Motivation
-----------
Fix potential bootstrapping failures if the SDK is in an environment that needs to use alternate addressing.
Changes
---------
* Consolidate logic to check for alternate address hostnames
* Check for alternate address hostnames when bootstrapping bucket

CXXCBC-487: Check if alternate addressing is used when bootstrapping

---

CMakeLists.txt
core/impl/collection.cxx
core/impl/internal_scan_result.hxx
core/impl/scan_result.cxx
core/meta/features.hxx
core/range_scan_orchestrator.cxx
core/range_scan_orchestrator.hxx
core/scan_result.cxx
core/scan_result.hxx
couchbase/collection.hxx
couchbase/scan_options.hxx
couchbase/scan_result.hxx
couchbase/scan_result_item.hxx
couchbase/scan_type.hxx
test/test_integration_range_scan.cxx

Range scan has been implemented in the core. It also needs to be exposed via the Public API.
* Added an async version of `core::range_scan_orchestrator.scan()`
* Add a `collection.scan()` method
* Added check for range scan bucket capability in `collection_impl.scan()` before executing the scan
* Add a `scan_type` abstract class with `range_scan`, `prefix_scan`, `sampling_scan` concrete subclasses, as well as `scan_options` which are used for the parameters of `collection.scan()`
* Add `scan_result` which is used for iterating through the results of the scan, either using `result.next()` or the input iterator `scan_options::iterator`. Each individual range scan result is of type `scan_result_item`.
All tests pass, including FIT.

CXXCBC-443: Public API for Range Scan

---

.clang-format
.github/workflows/linters.yml
core/crud_component.cxx

We must be careful when invoking items callback for the range scan results, as the whole iteration might be canceled after any of the invocation. The library should not be calling any callbacks on canceled request to avoid memory issues.
In particular the test "integration: range scan cancel during streaming using pending_operation cancel" uses stack-allocated vector for results, and cancels request during itertion. The range scan completed, but the library might still call the items callback, which will try to insert items into deallocated result vector.

CXXCBC-494: fix memory issue in range scan implementation

---

core/operations/document_query.cxx
core/operations/document_query.hxx
couchbase/query_options.hxx
tools/query.cxx

We can't distinguish whether the user explicitly set `profile` in the query options to 'off' or if it was left as the default value.
Make `profile` optional in the core `query_request` which is only set if the user specifies the profile in the Public API's query options. Always send the profile parameter to the server if the user has set its value.
All test cases in FIT's `QueryParametersTest` pass

CXXCBC-470: Distinguish between 'unset' and 'off' query_profile

---

core/collections_component.cxx

The retry strategy for `get_collection_id` is currently being ignored. It should be used if set, otherwise use the default retry strategy specified for the `collections_component`.

CXXCBC-492: Use retry strategy in collections_component's get_collection_id

---

core/bucket.cxx
core/io/mcbp_session.cxx

Motivation
==========
Server versions prior to 7.6.2 (MB-60405) can sometimes provide a configuration that has a vBucketMap, but it does not contain any vbuckets. This should not happend, but since it does the SDK should ignore these configurations.
Changes
=======
Ignore a configuration if it contains an empty vBucketMap.

CXXCBC-503: Ignore configuration if it contains an empty vBucketMap

---

core/error_context/analytics_json.hxx
core/error_context/http_json.hxx
core/error_context/query_json.hxx
core/error_context/search_json.hxx
core/impl/cluster.cxx
core/impl/error.cxx
core/impl/error.hxx
core/impl/retry_reason.cxx
core/impl/retry_reason.hxx
core/impl/scope.cxx
couchbase/analytics_options.hxx
couchbase/base_error_context.hxx
couchbase/cluster.hxx
couchbase/error.hxx
couchbase/error_context.hxx
couchbase/query_options.hxx
couchbase/retry_reason.hxx
couchbase/scope.hxx
couchbase/search_options.hxx
test/test_integration_analytics.cxx
test/test_integration_examples.cxx
test/test_integration_search.cxx
tools/analytics.cxx
tools/pillowfight.cxx
tools/query.cxx

Changes:
- Convert query, search & analytics to use couchbase::error
- Add assign & as() methods for JSON conversion for analytics, search, query (and http) error contexts
- Add make_error util methods
- Add as() method to error context

CXXCBC-499 Use couchbase::error for Query, Search and Analytics operations

---

test/test_integration_subdoc.cxx

Appears this issue has been fixed since the ticket was created, so adding test to confirm behaviour.
Changes:
- Added test using lookup_in_specs in a mutate_in_request
Results:
- All tests pass

CXXCBC-30 Inconsistent behaviour when using subdoc opcodes incorrectly

---

test/test_integration_management.cxx
test/utils/server_version.hxx

A scoped endpoint for `analyze_document` was added in [MB-60643](https://issues.couchbase.com/browse/MB-60643). We should skip the tests for versions earlier than that.

Add feature check for scoped analyze_document in tests

---

core/io/mcbp_session.cxx
core/protocol/cmd_cluster_map_change_notification.cxx
core/protocol/cmd_cluster_map_change_notification.hxx
core/protocol/cmd_get_cluster_config.cxx
core/protocol/cmd_get_cluster_config.hxx

Motivation
==========
Being able to dump the cluster configuration is a useful debugging tool. An unfortunate side effect is the config is not properly trimmed when prepped to output in the log.  Removing the unwanted bytes in the log helps improve dev experience.
Changes
=======
* Update cmd_cluster_map_change_notification and cmd_get_cluster_config to save parsed config body as std::string_view.
* Update mcbp session to use new config_text from corresponding request/response.

CXXCBC-523: Clean up dump_configuration config output

---

core/range_scan_orchestrator.cxx
core/transactions/staged_mutation.cxx

```
core/range_scan_orchestrator.cxx:417: warning: Lock Consistency Violation
Read/Write race. Non-private method `couchbase::core::range_scan_orchestrator_impl::is_cancelled` reads without synchronization from `this->cancelled_`, which races with the write in method `couchbase::core::range_scan_orchestrator_impl::stream_failed`. 
415.     bool is_cancelled() override
416.     {
417.         return cancelled_;
^
418.     }
419. 
core/range_scan_orchestrator.cxx:423: warning: Lock Consistency Violation
Read/Write race. Non-private method `couchbase::core::range_scan_orchestrator_impl::next` indirectly reads without synchronization from `this->cancelled_`, which races with the write in method `couchbase::core::range_scan_orchestrator_impl::stream_failed`. 
421.     {
422.         auto …
```

lint: fix "Lock Consistency Violation" warnings

---

test/test_unit_binary_transcoder.cxx

error: useless cast to type ‘void’ in test/test_unit_binary_transcoder.cxx

Fix test build issue on CentOS 8

---

core/io/http_command.hxx
core/io/http_session.hxx
core/io/http_session_manager.hxx

Motivation
==========
The client does not currently attempt to retry if the HTTP session fails to resolve or connect.  Adding retries will help to improve user experience.
Changes
=======
* Add retries if resolve or connect fails.
* If connect fails, and resolve provided multiple endpoints, attempt to connect to next endpoint in list of provided endpoints.
* If ping() fails due to resolve/connect issue, list "attempted" hostname and port in `remote_address` property of `endpoint_ping_info`

CXXCBC-517:  Add HTTP session retries

---

core/transactions/attempt_context_impl.cxx

Capturing the transaction_operation_failed so the correct op_completed_with_error overload is called

Fix insert_raw_with_query transaction_operation_failed bug

---

core/impl/transaction_get_result.cxx
core/meta/features.hxx
core/transactions/transaction_get_result.hxx
couchbase/transactions/transaction_get_result.hxx
examples/async_game_server.cxx
examples/game_server.cxx
test/test_transaction_examples.cxx
test/test_transaction_public_async_api.cxx
test/test_transaction_public_blocking_api.cxx
test/test_unit_transaction_utils.cxx

* Remove `content()` overloads that are not in spec.
* Rename `content` to `content_as`
* Rename `key()` to `id()`
* Make bucket/scope/collection accessors private

Finalize transaction_get_result API

---

core/impl/cluster.cxx
core/impl/scope.cxx
couchbase/cluster.hxx
couchbase/get_all_replicas_options.hxx
couchbase/get_any_replica_options.hxx
couchbase/lookup_in_all_replicas_options.hxx
couchbase/lookup_in_any_replica_options.hxx
couchbase/scope.hxx
couchbase/search_request.hxx
couchbase/vector_query.hxx
couchbase/vector_search.hxx

Changes:
- Bumped vector search, binary transactions & zone-aware replica reads to committed stability level
- Removed `search_query()`, in favour of `search()`

CXXCBC-528: SDK API 3.6 Release Preparation Stability levels

---

core/impl/disjunction_query.cxx
test/test_unit_search.cxx

'min' should be encoded in the request, and defaults to 1: [RFC](https://github.com/couchbaselabs/sdk-rfcs/blob/master/rfc/0052-sdk3-full-text-search.md#disjunctionquery)

CXXCBC-530: Include 'min' parameter when encoding disjunction FTS queries

---

core/transactions/attempt_context_impl.cxx
core/transactions/attempt_context_impl.hxx

This patch is only fixes problem with invoking null-callback. [CXXCBC-534](https://issues.couchbase.com/browse/CXXCBC-534) remains open as the whole design of the error caching has to be improved to avoid copies.

CXXCBC-534: Fix callbacks to avoid bad_function_call exception

---

core/impl/query.cxx
core/impl/transaction_op_error_category.cxx
core/transactions/attempt_context_impl.cxx
core/transactions/exceptions.cxx
couchbase/error_codes.hxx
test/test_transaction_public_blocking_api.cxx

Changes:
- Replaced transaction_op::unknown with transaction_op::generic
- Removed FIT-specific not_set & couchbase_error from errc::transaction_op

Do not expose FIT-specific transaction errors in public API

---

.github/workflows/columnar.yml
CMakeLists.txt
bin/build-tests
core/cluster.cxx
core/cluster.hxx
core/cluster_options.hxx
core/columnar/background_bootstrap_listener.hxx
core/columnar/bootstrap_notification_subscriber.hxx
core/columnar/security_options.hxx
core/http_component.cxx
core/impl/bootstrap_error.hxx
core/io/config_tracker.cxx
core/io/config_tracker.hxx
core/io/http_command.hxx
core/io/http_session_manager.hxx
core/io/mcbp_session.cxx
core/io/mcbp_session.hxx
core/origin.cxx
core/timeout_defaults.hxx
core/utils/connection_string.cxx

Motivation
==========
Columnar SDKs takes a different approach to connect. So that wrapper SDKs can still utilize the majority of the I/O functionality in the C++ client, the Columnar connect changes should be added.
Changes
=======
* Add path to allow SDKs to open and bootstrap a cluster in the background
* Add "infinite" retries when bootstrapping
* Add config_tracker
* Add functionality to track bootstrap failure/success
* Add deferred queue for HTTP requests

CXXCBC-525: Columnar - open cluster connection in background

---

core/io/http_session.cxx
core/io/http_streaming_response.cxx
core/io/http_streaming_response.hxx

If the entire HTTP body has been read in the initial read before returning the HTTP streaming response, any subsequent attempt to read from the TCP socket will never return.
* Set `reading_complete` when initializing `http_streaming_response_body` with the value of `http_streaming_parser`'s `complete` field.
* Call the `stream_end_handler` when the entire HTTP message has been read successfully (not only on cancellation).

Fix behaviour when reading is complete before returning HTTP streaming resp

---

core/io/http_session_manager.hxx

Fixed use-after-move issue reported by clang-tidy

CXXCBC-550: capture command instead of handler

---

core/http_component.cxx

It is good practice to capture optional into local variable and check that before usage. Otherwise it might become empty potentially (and clang-tidy complains about it)

Explicitly check optional for clang-tidy

---

CMakeLists.txt
core/columnar/error.cxx
test/test_integration_columnar.cxx

* The error context is now represented by a `tao::json::value` instead of `std::map<std::string, tao::json::value>`
* Add `message_with_ctx()` helper for getting the error message that includes the serialized error context, as that's the only way the error context will be exposed from the wrappers.

Add helper method for serializing ctx into columnar error msg

---

cmake/0001-fix-build-for-mingw-w64-ucrt-x86_64-toolchain.patch

This is necessary to fix Ruby build on Windows

Revert 13186f3 for 0001-fix-build-for-mingw-w64-ucrt-x86_64-toolchain.patch

---

core/cluster.cxx
core/io/config_tracker.cxx
core/io/config_tracker.hxx

Motivation
==========
After bootstrap completes, for alternate addressing, cluster options can be updated.  However, currently for the Columnar connection path those cluster options are not propagated to the HTTP session manager.  The lack of propagation means HTTP connections are not able to connect when using alternate addressing because the external hostname and/or port is not used.
Changes
=======
* For Columnar connections, pass the updated cluster options back in the create_sessions() callback so that the options can be propagated to the HTTP session manager.

CXXCBC-562: (Columnar) Provide HTTP session manager with updated cluster

---

CMakeLists.txt
core/columnar/agent.cxx
core/columnar/backoff_calculator.cxx
core/columnar/backoff_calculator.hxx
core/columnar/error.hxx
core/columnar/query_component.cxx
core/columnar/query_component.hxx
core/columnar/retry_info.hxx
core/free_form_http_request.hxx
core/http_component.cxx
core/io/http_session_manager.hxx
core/pending_operation_connection_info.hxx
test/CMakeLists.txt
test/test_integration_columnar_query.cxx
test/test_integration_http_session_manager.cxx
test/test_unit_columnar_retry.cxx
test/utils/integration_test_guard.cxx
test/utils/integration_test_guard.hxx

* Refactor columnar query execution into a `pending_query_operation` in query_component, to enable handling retries
* Implement exponential backoff with full jitter and use it for columnar query retries if all errors have `is_retriable == true`
* Add a randomly generated client-context-id to the query request (include in payload & logging)
* Extend `session_manager->check_out()` to allow specifying an 'undesired' node. If other nodes for the required service exist, any other node will be selected at random. This is used for columnar query retries.

CXXCBC-543: Add retries for columnar query

---

core/columnar/agent.cxx
core/columnar/agent_config.cxx
core/columnar/agent_config.hxx
core/columnar/query_component.cxx
core/columnar/query_component.hxx
core/http_component.hxx
test/test_integration_columnar_query.cxx

Add timeout options to the `columnar::agent_config`. Currently only the `query_timeout` is used, as the cluster is opened separately outside the agent. When we create an entry point for opening the cluster through `columnar::agent` we will use the other timeouts as well.

CXXCBC-557: Add global columnar timeout config

---

.gitignore
core/transactions/atr_cleanup_entry.cxx
core/transactions/attempt_context_impl.cxx
core/transactions/attempt_context_impl.hxx
core/transactions/document_metadata.hxx
core/transactions/internal/transaction_context.hxx
core/transactions/internal/transactions_cleanup.hxx
core/transactions/staged_mutation.cxx
core/transactions/staged_mutation.hxx
core/transactions/transaction_context.cxx
core/transactions/transaction_get_result.cxx
core/transactions/transaction_get_result.hxx
core/transactions/transaction_links.cxx
core/transactions/transaction_links.hxx
core/transactions/transactions_cleanup.cxx
test/test_transaction_context.cxx
test/test_transaction_simple.cxx
test/test_transaction_simple_async.cxx

The attempt object does not own the transaction context, so it should use weak_ptr instead.

CXXCBC-569: resolve cycle in shared pointers for transaction_context

---

core/cluster.cxx
core/columnar/error_codes.cxx
core/columnar/error_codes.hxx
core/columnar/query_component.cxx
core/columnar/query_result.cxx
core/io/http_session.cxx
core/io/http_session.hxx
core/io/http_session_manager.hxx
test/test_integration_columnar_query.cxx

When `cluster.close()` is called, all in-progress HTTP operations should be cancelled.
* Add `pending_sessions_` in the HTTP session manager to ensure that it has a reference to sessions created by it at all stages of their lifetime. Pending operations are the sessions that are currently connecting (i.e. after they have been removed from `idle_sessions_` or created and before being added to `busy_sessions_`)
* Fix issue where the callback was not called in the case of a timeout (dispatch timeout or overall timeout) while a session is connecting.
* In an HTTP session that is connecting, call the connect callback if it is stopped before it has connected.
* Add the `couchbase::core::columnar::client_errc` error codes to represent errors that are not the result of a client-server interaction. …

CXXCBC-576: Ensure all HTTP sessions are stopped when closing the core cluster

---

core/platform/string_hex.h

`std::string` is used in this header. We should add `#include <string>`

Include `<string>` in string_hex.h

---

core/columnar/query_component.cxx
core/columnar/retry_info.hxx
core/platform/string_hex.h

The Error/Retry handling RFC Revision 8 requires that we list the last error code & message that was retried when reporting a timeout
* Include a `last_errors` field in the error context that lists the set of server errors that were retried, when the error is a timeout resulting from retries.
* FIX: Timeout should be initialized before the HTTP request in `pending_query_operation`
Tested with [FIT](https://review.couchbase.org/c/transactions-fit-performer/+/215117) (via Python) - test passed

CXXCBC-580: Report last error when timing out on columnar query retries

---

core/impl/cluster.cxx
couchbase/behavior_options.hxx
couchbase/network_options.hxx
tools/utils.cxx
tools/utils.hxx

Deprecates behavior_options#network() in favor to network_options#preferred_network()

CXXCBC-552: cleanup network selection options

---

core/columnar/error.hxx
core/columnar/query_component.cxx
core/free_form_http_request.hxx
core/http_component.cxx
test/test_integration_columnar_query.cxx

* Update the timeout written in the query request payload when retrying, according to the time remaining until the deadline.
* Fix a bug where not setting the timeout in the options (i.e. relying on the cluster-wide default) resulted in the query timing out immediately.
* This is because the HTTP component's timeout would not be set, which resulted in the epoch being passed on to the http_session_manager's `connect_then_send_pending_op` as the deadline.
* The timeout is now always sent to the HTTP component.
* Remove the dispatch timeout test which was succeeding because of the bug above. Dispatching appears to succeed very quickly, so even with a timeout 1ms the test was not consistently passing - we probably need to find another way to test it.
* Use the default timeouts in tests that …

CXXCBC-588: Update timeout sent to server on each columnar query retry

---

docs/cbc-analytics.md
docs/cbc-get.md
docs/cbc-pillowfight.md
docs/cbc-query.md
tools/utils.cxx

To ensure that profile works, we must apply it the options as the very last step, because the way how CLI parser works, the switches are always populated, either by user value or by default. And being --configuration-profile switch itself, we cannot update defaults for other switches at before the parsing stage, therefore we left with the only option to defer profile application to the very last step.

CXXCBC-593: apply configuration profile as the last step

---

CMakeLists.txt
core/columnar/agent.cxx
core/columnar/agent_config.cxx
core/columnar/agent_config.hxx
core/columnar/database_management_options.hxx
core/columnar/management_component.cxx
core/columnar/management_component.hxx
core/columnar/query_component.hxx
core/columnar/query_options.hxx
core/free_form_http_request.cxx
core/free_form_http_request.hxx
core/http_component.cxx
core/http_component.hxx
core/io/http_streaming_response.cxx
test/CMakeLists.txt
test/test_integration_columnar_management.cxx
test/test_integration_columnar_query.cxx

* Add a `buffered_http_request` option in the HTTP component, that we can use for management operations that don't require streaming
* Add a columnar management component, that currently has support for all database management operations listed in the RFC

CXXCBC-577: Add columnar database mangement operations

---

core/columnar/query_component.cxx

Columnar Error/Retry RFC revision 9:
> If the list of errors in a query response contains at least one non-retriable error, the first non-retriable error in the array is selected. Otherwise, the first retriable error in the array is selected. 
* Report the first non-retriable error in the columnar query error properties, if it exists. Otherwise, report the first error.
FIT tests pass (Tested via the Python SDK)

CXXCBC-602: Columnar - report first non-retriable code/message in query error

---

core/utils/connection_string.cxx
test/test_unit_connection_string.cxx

Changes
=======
* Enforce allowed connection string options for Columnar
* Enforce golang duration syntax for timeout options (e.g. don't default to millis)
* Update connstr tests

CXXCBC-599: Update allowed connection string options

---

core/io/mcbp_session.cxx
core/io/streams.hxx

* remove `reopen()` API of the stream, the close is asynchronous anyway, so it is not correct to assume that the socket will be ready immediately.
* remove `open_` flag for stream, and instead proxy it directly to the socket to avoid "operation is already in progress" type of errors when trying to open the same socket twice.
* re-arm `connection_deadline_` when the socket is ready for data, use KV timeout for whole handshake with the single node. Re-initiate bootstrap using next bootstrap address in case of single node timeout.
* reset `reading_` flag in case of error. Ensure that the flag is reset if the session is not reading.
* handle `socket_closed_while_in_flight` error, and if it happens during bootstrap, try next node in the list, otherwise preserve old behavior (close the …

CXXCBC-606: Fix detection of disfunctional node

---

CMakeLists.txt
core/bucket.cxx
core/bucket.hxx
core/cluster.cxx
core/io/http_command.hxx
core/io/http_session_manager.hxx
core/io/mcbp_command.hxx
core/metrics/meter_wrapper.cxx
core/metrics/meter_wrapper.hxx
core/topology/configuration.hxx
core/topology/configuration_json.hxx
test/CMakeLists.txt
test/test_integration_meter.cxx
test/test_unit_metrics.cxx
test/utils/server_version.hxx

The Extended Observability RFC revisions 24 & 25 require us to record additional metrics tags: bucket, scope, collection, outcome, and cluster labels (name & UUID)
* Update config parsing to include `clusterName` & `clusterUUID`
* Create a new `core::metrics::meter_wrapper` class that watches for config updates and keeps track of cluster labels 
* Replace all meter references in the core with the meter wrapper
* The meter wrapper is responsible for encoding the metric attributes & inserts tags for the cluster labels, if those are supported by the cluster
* Add some tests for KV
Tests pass
Non-KV operation metrics don't currently report collection, bucket and scope names.

CXXCBC-582: Add cluster labels, keyspace & outcome in metrics

---

core/impl/observe_poll.cxx
core/impl/observe_poll.hxx

The context lifetime is being prolonged because of the `on_last_response_` not being fired. The issue is reproducible when only one round is necessary to meet persistence conditions.

CXXCBC-614: fix memory leak in observe_poll

---

core/operations/management/analytics_link_get_all.cxx
core/operations/management/analytics_link_get_all.hxx
test/test_integration_management.cxx

Changes
=======
* Allow link_type, link_name and dataverse_name to be optional
* Raise invalid_argument if a link_name is provided but a dataverse_name is not

CXXCBC-620: Update core analytics_link_get_all to follow RFC

---

core/transactions/async_attempt_context.hxx
core/transactions/attempt_context.hxx
core/transactions/attempt_context_impl.cxx
core/transactions/attempt_context_impl.hxx
core/transactions/transaction_context.cxx
core/transactions/transaction_get_result.hxx
test/test_transaction_context.cxx
test/test_transaction_simple.cxx
test/test_transaction_simple_async.cxx

* Expose `insert_raw` and `replace_raw` in the core txns attempt context APIs, which have now been renamed to `insert` and `replace`.
* Remove the variants of `insert` and `replace` that use transcoders from the core API, as well as the overloads of `core::transactions::transaction_get_result::content()` that use transcoders
* The C++ Public API, as well as the wrappers, have their own transcoder support, which makes these redundant.

CXXCBC-615: Expose insert_raw & replace_raw in core txns attempt ctx

---

core/meta/features.hxx
couchbase/metrics/otel_meter.hxx

The integration with the OpenTelemetry Metrics API was written before the Otel Metrics API was GA'd (< 1.7.0). Update it to support the latest Metrics API that is now stable.
* Replace usage of `opentelemetry::metrics::Meter::CreateLongHistogram` with `opentelemetry::metrics::Meter::CreateUint64Histogram`

CXXCBC-622: Update OpenTelemetry metrics integration to use GA Metrics API

---

core/impl/analytics.cxx
core/impl/collection.cxx
core/impl/query.cxx
core/impl/search.cxx
core/meta/features.hxx
couchbase/common_options.hxx

* Add a `parent_span` setter to all Public API options classes (by adding it to the `common_options` base class) – at 'volatile' stability
* Map the option to the corresponding Core API field where it is available

CXXCBC-609: Expose `parent_span` in Public API options

---

core/impl/error.cxx
test/test_integration_analytics.cxx
test/test_integration_management.cxx
test/test_integration_transcoders.cxx

Changes:
- Only run `build_error_context` if the `std::error_code` is non-zero

CXXCBC-627: Performance degradation after couchbase::error changes

---

core/transactions/internal/transaction_context.hxx
core/transactions/transaction_context.cxx

- Exposed `get_replica_from_preferred_server_group` in `transaction_context`

CXXCBC-636: Expose preferred server group replica reads in transaction_context

---

.github/workflows/columnar.yml
.github/workflows/linters.yml
.github/workflows/sanitizers.yml
.github/workflows/tests.yml
.github/workflows/windows.yml
core/bucket.cxx
core/bucket.hxx
core/cluster.cxx
core/cluster.hxx
core/impl/collection.cxx
core/impl/observe_poll.cxx
core/impl/replica_utils.cxx
core/impl/replica_utils.hxx
core/operations/document_get_all_replicas.hxx
core/operations/document_get_any_replica.hxx
core/operations/document_lookup_in_all_replicas.hxx
core/operations/document_lookup_in_any_replica.hxx
test/test_integration_range_scan.cxx

For performance reasons, store bucket configuration as shared pointer, and copy it instead. The SDK can use shared pointer here, as configuration is readonly, and only access to the pointer have to be protected by the mutex

CXXCBC-646: Do not copy configuration when the operation depends on it

---

core/meta/features.hxx

FIT performer need it to compile, as it must support both old and new version of the core

CXXCBC-646: add feature flag for FIT performer

---

core/meta/features.hxx

FIT performer need it to compile, as it must support both old and new version of the core
Backport of #720

[backport] CXXCBC-646: add feature flag for FIT performer

---

core/logger/logger.cxx

All code paths must use update_file_logger to ensure thread safety. The create_file_logger just updated the logger pointer without incrementing version.
Backport of #722

[backport] CXXCBC-660: Fix potential race condition in the logger

---

core/operations/document_lookup_in.cxx
core/operations/document_lookup_in_all_replicas.hxx
core/operations/document_lookup_in_any_replica.hxx
core/operations/document_mutate_in.cxx
test/test_integration_subdoc.cxx

Changes
=======
* For subdoc operations, if no specs are provided raise and `invalid_argument` error instead of crashing on an assert.
* Add tests to confirm functionality.

CXXCBC-657: Raise InvalidArgument error if empty subdoc specs

---

cmake/couchbase_cxx_client.pc.in

couchbase_cxx_client.pc have to use absolute path for libdir

[backport] CXXCBC-666: Fix pkg-config file

---

cmake/couchbase_cxx_client.pc.in

couchbase_cxx_client.pc have to use absolute path for libdir

CXXCBC-666: Fix pkg-config file

---

core/websocket_codec.cxx

In some cases, when websocket_code is the first ever to touch RandomGenerator, the library might crash trying to dereference null pointer. It does not happen often, but in case of the one-shot applications it might happen (for example 'cbc get' from the tools)

CXXCBC-668: ensure random generator is initialized in websocket_codec

---

core/operations/document_get_all_replicas.hxx
core/operations/document_lookup_in_all_replicas.hxx

Currently, we only report an error if the last individual get/get_replica response to be received had an error. This means that if we have partial results, whether they are returned or not depends on the order at which we receive the responses, which is not deterministic.
If some successful replica results exist, always return them. We do this by only returning the error context of the last response (which is what we have been using to return an error from the overall operation), if there are no successful replica results.

CXXCBC-665: Always return partial results for all_replica ops if some get_replica reqs succeeded

---

core/impl/bucket_manager.cxx
core/management/bucket_settings.hxx
core/management/bucket_settings_json.hxx
core/meta/features.hxx
core/operations/management/bucket_create.cxx
core/operations/management/bucket_update.cxx
couchbase/management/bucket_settings.hxx

From Morpheus, the server is adding support for creating Magma buckets with 128 vBuckets. We are adding a `num_vbuckets` parameter to `bucket_settings` to allow configuring the number of vbuckets to either 128 or 1024.
Add `num_vbuckets` to `bucket_settings` in both the core and public APIs
All FIT tests pass

CXXCBC-654: Add num_vbuckets to bucket_settings

---

bin/init-cluster

We have some failing tests on Jenkins because cbdyncluster clusters don't have a cluster name set by default. The relevant tests are:
* integration: enable external tracer.integration: enable external tracer
* integration: use external meter.integration: use external 
They are failing because they expect the `db.couchbase.cluster_name` field to be populated for server versions where the cluster name is reported in the config.
We should set it in init-cluster if it's not already set.

CXXCBC-674: Set cluster name in init-cluster if supported & not already set

---

.github/workflows/columnar.yml
.github/workflows/linters.yml
.github/workflows/tests.yml

Ubuntu 20.04 runners have now been retired and removed.

Bump Ubuntu version used in GHA workflows

---

core/transactions/attempt_context_impl.cxx
core/transactions/staged_mutation.cxx
core/transactions/staged_mutation.hxx
test/test_transaction_public_blocking_api.cxx

The `transaction_get_result` returned from `ctx.replace()` or `ctx.insert()` does not include the post-operation content. Instead it includes the pre-replace content or an empty content respectively. The specification expects that the post-operation content is returned.
* Update insert/replace results in the create staged replace/insert methods to include the post-operation content.
* Store the pre-transaction user flags in the staged mutation, so they can be accessed when rolling back replace or remove operations via `staged_mutation::current_user_flags()`
* Add assertions to the relevant tests checking that the updated body was returned.

CXXCBC-682: Transaction replace/insert result should include post-op content

---

core/transactions/attempt_context_impl.cxx
core/transactions/attempt_context_impl.hxx
core/transactions/staged_mutation.cxx
core/transactions/staged_mutation.hxx

With ExtReplaceBodyWithXattr we can now avoid storing the staged content inside staged_mutation. We still always include the entire transaction_get_result inside a staged_mutation, which is not needed, as we only use a subset of the fields from the transaction_get_result. Storing those fields directly (similar to Go or Java), will allow us to further reduce the memory used for staged mutations.
* Remove the `transaction_get_result` from `staged_mutation`
* Add the individual fields, which were previously part of `transaction_get_result` that we need directly into the `staged_mutation`

CXXCBC-681: Do not store entire transaction_get_result in staged mutations

---

core/meta/features.hxx
core/operations/document_analytics.cxx
core/operations/document_query.cxx
couchbase/analytics_options.hxx
couchbase/query_options.hxx
test/test_integration_analytics.cxx
test/test_integration_query.cxx

The query and analytics services allow queries that have named and positional parameters in the same request. We should allow users to make queries with both types of parameters.
**Public API:**
* Update `query_options` & `analytics_options` so that setting named parameters doesn't clear any existing positional parameters and vice versa.
* Document the fact that setting positional parameters overrides existing positional parameters, and setting named parameters overrides existing named parameters.
**Core API:**
* Update encoding of query/analytics_query requests so both named and positional parameters are included in the payload if both have been set.

CXXCBC-684: Allow setting both named and positional parameters for queries

---

core/meta/features.hxx
couchbase/analytics_options.hxx
couchbase/query_options.hxx
test/test_unit_query.cxx

Our existing high-level `positional_parameters` and `named_parameters` setters require the number of parameters to be known at compile time. While `encoded_positional_parameters` and `encoded_named_parameters` can be used if the number of parameters is not known at compile time, that's a low-level uncommitted API, so we should provide a high-level alternative.
Add new methods to `analytics_options` & `query_options` – `add_named_parameter`, `add_positional_parameter`, `clear_positional_parameters`, and `clear_named_parameters`.
These allow any number of parameters to be set even when that's not known at compile time, without the user having to serialize them.

CXXCBC-672: Add `add_named_parameter` and `add_positional_parameter` to query/analytics options

---

core/transactions/attempt_context_impl.cxx
test/test_transaction_public_blocking_api.cxx
test/utils/server_version.hxx

Instead of using the CAS from the existing staged mutation, we should use the CAS from the `transaction_get_result` that was given to the replace operation. The original behavior of using the CAS from the staged mutation is considered a spec bug.
A benefit of this approach is that post-ExtReplaceBodyWithXattr, the `transaction_get_result`, if fetched via a txn get operation, will come from a server read, which will include an up-to-date CAS. This means that the transaction will not fail if the document was “illegally” inserted outside the transaction after the transaction had created the staged insert.
The user will either have done a transactional get after the transactional insert to get the `transaction_get_result` passed to the replace, or have given the `transaction_get_result` that …

CXXCBC-683: Txn replace - Use CAS from given TransactionsGetResult when document is a staged insert

---

core/io/mcbp_session.cxx
couchbase/wan_development_configuration_profile.hxx

Also this patch avoids to reuse connection timer for resolve and connect timeouts. With clean separation it is now easier to trace these events.

CXXCBC-700: update wan_develpment profile for public API

---

core/transactions/attempt_context_impl.cxx
core/transactions/exceptions.hxx

According to the [specification](https://github.com/couchbaselabs/couchbase-transactions-specs/blob/dd156f0a0ecbfc78d7c442433932c390ccf61892/transactions-stages.md?plain=1#L867), the SDK shouldn't wrap `document_unretrievable` errors in a `transaction_operation_failed` error:
> If lookupInAnyReplica() raises `DocumentUnretrievableException` or `FeatureNotAvailable`, this is raised directly to the lambda.  E.g. this joins the very small list of cases where failures to not set internal state that guarantees this attempt will fail, and allows the user to catch and ignore the error (and more usefully - to fallback to a regular ctx.get()).
Currently, we correctly don't cache the error internally, which allows users to 'catch' it, but we still wrap it in `transaction_operation_failed`. The …

CXXCBC-704: Return unwrapped document_unretrievable error from get_replica_from_preferred_server_group

---

core/transactions/get_multi_orchestrator.cxx

Fetching a replica now raises a document_unretrievable error that is not wrapped in a transaction_operation_failed. The get_multi error handling should be updated to handle that.
In get_multi_orchestrator's classify_error method, add handling for `op_exception`
ExtGetMultiMissingDocsTest which was previously failing now passes

CXXCBC-704: Handle document_unretrievable from get_multi individual fetch

---

core/transactions/transaction_get_multi_replicas_from_preferred_server_group_result.hxx
core/transactions/transaction_get_multi_result.hxx
couchbase/transactions/transaction_get_multi_replicas_from_preferred_server_group_result.hxx
couchbase/transactions/transaction_get_multi_result.hxx

The `exists` method in transactions get_multi results is always returning `false`, as `spec_index >= content_.size()` is _always_ false for valid spec indexes.

CXXCBC-709: Fix exists() in transactions get_multi result

---

.github/workflows/windows.yml

Windows Server 2019 runners have been retired

GHA: Remove windows-2019 & add windows-2025

---

core/impl/error.cxx
core/transactions/exceptions.cxx
core/transactions/exceptions.hxx
core/transactions/internal/exceptions_internal.hxx

Motivation
----------
Exception propagation FIT tests were failing, which uncovered that we were setting the NOT_SET external exception to a generic error code
Changes
-------
Change NOT_SET to return an unset error code, including the conversion function

CXXCBC-420: external_exception NOT_SET should not set to generic error code

---

core/operations/management/search_index_get_all.cxx

Changes
=======
* Do not return an error if/when indexDefs are empty/null.  Instead return w/ an empty list of index definitions.

CXXCBC-693: Handle empty/null indexDefs for search_index_get_all

---

core/app_telemetry_meter.cxx
core/app_telemetry_meter.hxx

When a report is generated, we replace the existing `app_telemetry_meter_impl` with a new instance of a `default_app_telemetry_meter_impl`. This means that the existing node labels cache will be empty, until a new config is seen, and any subsequent reports will possibly have empty `node` and `alt_node` attributes.
* When creating the new `default_app_telemetry_meter_impl` instance, set its node labels cache to the value it had in the old `app_telemetry_meter_impl` instance.
* Add a shared lock to protect the `impl_` pointer, as it can be modified and accessed from different threads at the same time.
ApplicationTelemetrySocketTest in FIT now passes, with the exception of some assertions failing due to [CXXCBC-650](https://jira.issues.couchbase.com/browse/CXXCBC-650).
[CXXCBC-650]: …

CXXCBC-651: Preserve cached node labels after generating report in app telemetry meter

---

core/app_telemetry_meter.cxx
core/app_telemetry_meter.hxx

[backport] CXXCBC-651: Preserve cached node labels after generating report in app telemetry meter

---

core/io/http_session_manager.hxx
tools/analytics.cxx

Motivation
==========
An HTTP workload can potentially use an invalid node index to access a node in the config in scenarios to where a node in the cluster has been failed over.
Changes
=======
* Upon updating the config w/in the HTTP Session manager, reset the next node index if its current value is greater than or equal to the number of nodes in the new config
* Update analytics tool to only populate error context if the analytics operation has an error

CXXCBC-715: Hard Failover Intermittent Crash

---

.github/workflows/tests.yml
bin/validate-test-labels
test/test_integration_analytics.cxx
test/test_integration_columnar_query.cxx
test/test_integration_query.cxx
test/test_integration_search.cxx
test/test_integration_subdoc.cxx
test/test_unit_management_search_index.cxx
test/test_unit_query.cxx

Some of our tests didn't have an 'integration' or 'unit' label. On GitHub Actions we use these labels to filter tests, which means that tests without a label weren't running on GHA.
Also added a script to verify that all tests have one of the known labels, to prevent any tests without a label from being added in the future.

Add labels to all tests

---

core/columnar/query_component.cxx
core/io/http_session_manager.hxx

Changes
=======
* Use std::move() to pass the callback provided to `connect_then_send_pending_op` when the session fails to connect and retries the call (using a new session)
* Do not invoke the callback if a deadline has been reached or the session was stopped.  The pending_http_operation already has hooks in play to handle these scenarios and attempting to invoke the callback from the session's connection callback and lead to UB.
* When a query times out, log the client_context_id as well.  This helps to pair the log message to when the query request was made.

CXXCBC-727: Columnar - fix how client handles connect_then_send_pending_op callback

---

test/test_integration_management.cxx

The max expiry update happens asynchronously, so it's possible to get the pre-update `max_expiry` from the `get_all_scopes` request that follows. Moving it inside the `wait_until` predicate addresses this issue.

Improve stability of update collection max expiry tests

---

.github/actions/create-cluster/action.yml
.github/actions/remove-cluster/action.yml
.github/workflows/sanitizers.yml
.github/workflows/tests.yml
test/test_integration_analytics.cxx
test/test_integration_arithmetic.cxx
test/test_integration_connect.cxx
test/test_integration_crud.cxx
test/test_integration_diagnostics.cxx
test/test_integration_durability.cxx
test/test_integration_management.cxx
test/test_integration_management_search_index.cxx
test/test_integration_query.cxx
test/test_integration_range_scan.cxx
test/test_integration_read_replica.cxx
test/test_integration_search.cxx
test/test_integration_subdoc.cxx
test/test_integration_transcoders.cxx
test/test_transaction_public_blocking_api.cxx
test/utils/integration_test_guard.cxx
test/utils/test_context.cxx

With this change our GHA workflows will use cbdinocluster to create Couchbase clusters, allowing to test against multi-node clusters, for which we currently rely on Jenkins.
In the future we can configure the workflows to test against pre-release versions, but for that we need to configure an access token in the repository's secrets.

CXXCBC-718: Use cbdinocluster for GitHub Actions

---

CMakeLists.txt
core/bucket.cxx
core/bucket.hxx
core/cluster.cxx
core/cluster_options.hxx
core/impl/public_cluster.cxx
core/io/mcbp_command.hxx
core/origin.cxx
core/orphan_reporter.cxx
core/orphan_reporter.hxx
core/tracing/constants.hxx
core/tracing/threshold_logging_options.hxx
core/tracing/threshold_logging_tracer.cxx
core/utils/concurrent_fixed_priority_queue.hxx
core/utils/concurrent_fixed_queue.hxx
test/CMakeLists.txt
test/test_helper.hxx
test/test_unit_orphan_reporter.cxx
test/test_unit_utils.cxx

When the capacity of the concurrent fixed queue is exceeded, and an item is emplaced, currently, it always drops an existing item and replaces it with a new item, irrespective of how the items compare. This results in the queue holding the last N items to be emplaced, rather the top N items.
* Turn the priority queue that the concurrent fixed queue uses internally into a min-heap. This allows the concurrent fixed queue to peek the smallest item and check whether it should be replaced with a new item that is being emplaced.
* Remove its `pop` method, as it's not possible to do that anymore with the internal representation being a min-heap. It's no currently used. The only way to access the data is via `steal_data` which transforms the data into a max-heap `std::priority_queue`.
* Rename …

CXXCBC-732: Fix bug where concurrent fixed queue doesn't correctly report top N items

---

.github/actions/create-cluster/action.yml
.github/workflows/sanitizers.yml
.github/workflows/tests.yml
bin/build-tests
bin/run-integration-tests
bin/run-unit-tests

* Add separate jobs for unit & integration tests. Unit tests don't need a cluster to be set up
* Add a build job in the tests & sanitizers workflows, all test runs use the build artifacts from that job, avoiding having to build the library repeatedly

CXXCBC-717: GHA - separate unit & integration test jobs

---

test/test_integration_management.cxx

The history retention setting update happens asynchronously, so it's possible to get the pre-update `history` from the `get_all_scopes` request that follows. Moving it inside the `wait_until` predicate addresses this issue.

Improve stability of update collection history ret test

---

core/io/http_command.hxx
core/io/mcbp_command.hxx
core/io/mcbp_session.cxx
core/io/mcbp_session.hxx
core/tracing/constants.hxx
core/tracing/threshold_logging_tracer.cxx
couchbase/tracing/request_span.hxx
test/test_integration_tracer.cxx

The Observability RFC expects having separate `dispatch_to_server` spans. Currently, we are recording all dispatch-level attributes on the top-level operation span.
* Add dispatch spans for KV operations, one span per server round-trip. Update the dispatch-level attribute names so they conform to the latest semantic conventions
* Update the threshold logging tracer so it can handle both the legacy top level spans that have dispatch-level attributes (temporarily, for compatibility with HTTP operations) and the new dispatch spans.
* Add "canonical" address & port fields to memd sessions, these are the default (non-external) hostname & port as they appear in the config, which are now being reported in the new `server.endpoint` and `server.port` dispatch span attributes.

CXXCBC-736: Add dispatch spans for KV operations
