couchbase/couchbase-cxx-client

- CMakeLists.txt
- README.md
https://issues.couchbase.com/browse/CXXCBC-14
In preparation for more work, making this PR to improve build instructions:
- Updated CMake version reference
- Added more instructions/clarifications to the README
> [CXXCBC-14] Update build instructions in preparation for test refactoring

- bin/check-clang-static-analyzer
- couchbase/io/http_session_manager.hxx
- test/CMakeLists.txt
- test/test_native_management.cxx
This change also fixes data race in HTTP manager.
> CXXCBC-13: add integration tests for bucket management APIs

- test/test_helper_native.hxx
- test/test_native_diagnostics.cxx
- test/test_native_management.cxx
- test/test_native_trivial_query.cxx
Similar to https://github.com/couchbaselabs/couchbase-cxx-client/pull/11, add the same for execute_http
> Add synchronous version of execute_http

- .gitmodules
In preparation for https://github.blog/2021-09-01-improving-git-protocol-security-github/
>  Fix github submodule cloning

- .gitmodules
- .idea/vcs.xml
- cmake/ThirdPartyDependencies.cmake
- couchbase/bucket.hxx
- couchbase/cluster.cxx
- couchbase/cluster.hxx
- couchbase/io/http_command.hxx
- couchbase/io/http_session.hxx
- couchbase/io/http_session_manager.hxx
- couchbase/io/mcbp_command.hxx
- couchbase/io/mcbp_session.hxx
- test/test_integration_trivial_crud.cxx
- test/test_integration_trivial_query.cxx
- test/utils/integration_shortcuts.hxx
in particular, allow to use lambdas that capture move-only objects as
operation handlers
> fix move semantics for handlers

- couchbase/operations/management/CMakeLists.txt
- couchbase/operations/management/cluster_describe.cxx
- couchbase/operations/management/cluster_describe.hxx
- test/test_integration_collections.cxx
- test/test_integration_crud.cxx
- test/test_integration_durability.cxx
- test/test_integration_management.cxx
- test/test_integration_query.cxx
- test/utils/integration_test_guard.cxx
- test/utils/integration_test_guard.hxx
- test/utils/server_version.hxx
fallback to version from environment only if the cluster does not agree
on version or returns invalid version string
> tests: try to detect cluster version using REST API

- couchbase/io/mcbp_session.hxx
Fixes this failure that happened recently
```
7/57 Test  #7: integration: analytics index management ..........................Subprocess aborted***Exception:   0.13 sec
[2021-12-16 09:55:51.235] [94669,94669] [debug] 0ms, [77400283-dc4d-4b91-4798-5ef483f70c3f/d22c2263-392f-43e1-7899-393db6f83ecf/plain/-] <172.23.111.139:11210> attempt to establish MCBP connection
[2021-12-16 09:55:51.235] [94669,94670] [debug] 0ms, [77400283-dc4d-4b91-4798-5ef483f70c3f/d22c2263-392f-43e1-7899-393db6f83ecf/plain/-] <172.23.111.139:11210> connecting to 172.23.111.139:11210
[2021-12-16 09:55:51.237] [94669,94670] [debug] 1ms, [77400283-dc4d-4b91-4798-5ef483f70c3f/d22c2263-392f-43e1-7899-393db6f83ecf/plain/-] <172.23.111.139:11210> connected to 172.23.111.139:11210
[2021-12-16 09:55:51.237] [94669,94670] …
```
> handle cluster_map_notification during MCBP session bootstrap

- test/test_integration_management.cxx
Simplify the logic (remove json parsing) for waiting for a search index to be online
```
[2021-12-16 14:42:38.677] [7520,7521] [debug] 100ms, [9db2ec7d-d789-41a2-7f46-63ab8ec3da8f/94f2909d-8aa5-4aec-8d91-fd3a3f0d8eba] connecting to 127.0.0.1:8094
[2021-12-16 14:42:38.677] [7520,7520] [trace] 0ms, [9db2ec7d-d789-41a2-7f46-63ab8ec3da8f/94f2909d-8aa5-4aec-8d91-fd3a3f0d8eba] HTTP request: search, method=GET, path="/api/stats/index/index_1642289402101", client_context_id="d43c1931-1f2a-4c63-39b5-a98b8962e451", timeout=75000ms
[2021-12-16 14:42:38.677] [7520,7521] [debug] 0ms, [9db2ec7d-d789-41a2-7f46-63ab8ec3da8f/94f2909d-8aa5-4aec-8d91-fd3a3f0d8eba] connected to 127.0.0.1:8094
[2021-12-16 14:42:38.683] [7520,7521] [trace] 5ms, [9db2ec7d-d789-41a2-7f46-63ab8ec3da8f/94f2909d-8aa5-4aec-8d91-fd3a3 …
```
> Ignore search index not online errors when analyzing document

- couchbase/operations/management/bucket_describe.cxx
- couchbase/operations/management/bucket_describe.hxx
- test/test_integration_management.cxx
- test/utils/integration_test_guard.hxx
- test/utils/server_version.hxx
Analytics is not supported with magma buckets
Analytics external link management is not supported with cert auth on versions < 7.1
> Skip tests that don't work in certain configurations

- couchbase/operations/management/bucket_create.cxx
- couchbase/operations/management/bucket_settings.hxx
- couchbase/operations/management/bucket_settings_json.hxx
Couchbase 7.1 will provide a developer preview feature that allows
buckets to have custom conflict resolution.  Providing the new type will
allow users to test out DP feature.
> CXXCBC-65: Add Custom member to Bucket Management ConflictResolutionType

- couchbase/operations/document_query.cxx
- couchbase/operations/document_query.hxx
- test/test_integration_query.cxx
- test/utils/server_version.hxx
https://github.com/couchbaselabs/sdk-rfcs/pull/111
> CXXCBC-68: implement perserve_expiry for query service

- couchbase/error_context/analytics.hxx
- couchbase/error_context/query.hxx
- couchbase/operations/document_analytics.cxx
- couchbase/operations/document_query.cxx
> Copy first error code and message into error context

- test/test_integration_management.cxx
Because the management APIs are async, some not found errors are expected occasionally. Retry these errors when they occur.
> SDKQE-2574: Retry management operations on expected errors

- .github/workflows/tests.yml
- .github/workflows/windows.yml
- bin/init-cluster
- test/test_integration_management.cxx
Also updated 6.6.4 to 6.6.5 and added 7.1.0
> use matrix strategy in workflows where it is possible

- test/utils/server_version.hxx
Analytics and eventing are only supported on enterprise edition.
> SDKQE-2706: supports_analytics and supports_eventing_functions should check edition

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
The content was adopted from https://github.com/couchbase/couchbase-jvm-clients/commit/afa6fffc3c23b5603a2c6a722c1c33ed0edf5da0
> Add CoC and Contributing Guide to follow Community Standards

- core/operations/management/query.hxx
- test/test_integration_query.cxx
Update `query.hxx` as @thejcfactor mentioned in https://github.com/couchbaselabs/couchbase-cxx-client/pull/254.
> Fixed some missing includes in newer files.

- core/config_profile.hxx
- test/test_unit_config_profiles.cxx
Motivation
==========
Match the RFC, now that it is finalized.
Modification
============
Updated several timeouts in the wan_development profile, updated tests to match.
Results
=======
Passing tests.
> CXXCBC-221: Update wan_development config profile

- core/cluster.hxx
Now, when we load system certificates automatically, we can relax requirement to pass trust certificate in the connection options.
Instead the library will issue log warning reminding to either pass server sertificate in the options, or register it in the system store.
> CXXCBC-235, CXXCBC-248: do not fail if trust certificate is not specified

- core/transactions/attempt_context_impl.cxx
- core/transactions/transactions.cxx
Turns out I'm blocking in transactions, so we can't {{asio::post}} instead.   Until the blocking code in transactions is refactored, we need to stick with detached threads.
> Revert move from thread.detach for now

- core/impl/dns_srv_tracker.cxx
* don't warn about "localhost" giving 0 SRV records (although still try to query DNS)
* don't warn about attempts returning 0 SRV records if ec is not an error
> don't log expected warnings in DNS resolver

- CMakeLists.txt
- core/transactions/attempt_context_impl.cxx
Simple fix - make sure tl/expected is in the target includes.   Also,
a small update to the query error handling in txns.   There will be
another round of it to get it completely compliant with the
documentation, but this is a reasonable first step.
> Issue with CMakeFile when including in other projects

- test/tools/tool_kv_loader.cxx
Small improvement, that makes it easier compare
perf output between fixes.
> allow kv_loader to exit after certain number ops executed

- core/platform/uuid.cc
> CXXCBC-283: perf. speed up uuid serialization to string

- core/error_context/analytics.hxx
- core/error_context/http.hxx
- core/error_context/query.hxx
- core/error_context/search.hxx
- core/error_context/view.hxx
- core/impl/subdoc/lookup_in_macro.cxx
- core/impl/subdoc/mutate_in_macro.cxx
- core/operations/management/analytics_problem.hxx
- core/operations/management/eventing_problem.hxx
- core/platform/base64.cc
- core/protocol/client_opcode.hxx
- core/protocol/cmd_info.hxx
- core/transactions/atr_ids.cxx
- core/utils/crc32.hxx
- core/utils/json_streaming_lexer.hxx
- core/utils/url_codec.cxx
- test/utils/integration_shortcuts.hxx
gcc 13 does not provide `cstdint` implicitly.
> fix build with gcc-13

- core/impl/query.cxx
- core/transactions.hxx
- core/transactions/attempt_context_impl.cxx
- core/transactions/attempt_context_impl.hxx
- core/transactions/exceptions.cxx
- core/transactions/exceptions.hxx
- core/transactions/internal/transaction_context.hxx
- core/transactions/transaction_get_result.hxx
- core/transactions/transactions.cxx
- couchbase/transactions.hxx
- couchbase/transactions/async_attempt_context.hxx
- couchbase/transactions/attempt_context.hxx
- couchbase/transactions/transaction_get_result.hxx
- couchbase/transactions/transaction_query_result.hxx
- couchbase/transactions/transaction_result.hxx
- examples/async_game_server.cxx
- examples/game_server.cxx
- test/test_transaction_transaction_public_async_api.cxx
- test/test_transaction_transaction_public_blocking_api.cxx
- test/test_unit_transaction_utils.cxx
Specifically, returning an error, result pair from the transaction
operations themselves, and the transactions.run as well.   Or the async
equivalent.
> CXXCBC-287 Public txn api should match the rest of cxx api

- core/impl/dns_srv_tracker.cxx
- core/io/dns_client.cxx
- core/io/dns_config.cxx
- tools/utils.cxx
It also adds more details to the log entries
> CXXCBC-333: fix parsing resolv.conf on Linux

- CMakeLists.txt
- core/cluster.hxx
- core/origin.cxx
- core/origin.hxx
The output looks like this:
```
[2023-06-07 20:05:11.629] [398300,398300] [debug] 2ms, open cluster, id: "afd048-7cbc-2049-e4bb-d81653a80d90f5", core version: "1.0.0-dp.6+4.afb6b84a", {"bootstrap_nodes":[{"hostname":"cb.gxprauxvcewmas.cloud.couchbase.com","port":"11207"}],"options":{"analytics_timeout":"75000ms","bootstrap_timeout":"10000ms","config_idle_redial_timeout":"300000ms","config_poll_floor":"50ms","config_poll_interval":"2500ms","connect_timeout":"10000ms","disable_mozilla_ca_certificates":false,"dns_config":{"nameserver":"8.8.8.8","port":53,"timeout":"500ms"},"dump_configuration":false,"enable_clustermap_notification":false,"enable_compression":true,"enable_dns_srv":true,"enable_metrics":true,"enable_mutation_tokens":true,"enable_tcp_keep_alive":true,"enable_tls":true,"enable_tr …
```
> CXXCBC-335: log connection options

- couchbase/codec/raw_binary_transcoder.hxx
- test/CMakeLists.txt
- test/test_unit_binary_transcoder.cxx
The issue was reported in https://github.com/couchbaselabs/couchbase-cxx-client/pull/453 initially.
> CXXCBC-382: Fix raw_binary_transcoder so that gets on binary data are possible

- core/bucket.cxx
- core/bucket.hxx
- core/io/mcbp_command.hxx
- core/io/mcbp_session.cxx
- core/io/retry_orchestrator.hxx
- core/protocol/client_request.hxx
Port patch from #468 to `main` branch
> add more information to diagnose timeouts on NMV responses

- core/bucket.cxx
- core/bucket.hxx
- core/cluster.cxx
- core/cluster.hxx
- core/io/http_session_manager.hxx
- core/io/mcbp_session.cxx
- core/io/mcbp_session.hxx
- test/test_integration_diagnostics.cxx
* Add option for timeout in ping operations
* Set the ping status to `timeout` if the error code was a timeout
> CXXCBC-100: Add ability to set timeout for ping

- CMakeLists.txt
- core/impl/doc_id_query.cxx
- core/impl/search_row_location.cxx
- core/impl/search_sort_geo_distance.cxx
- core/meta/features.hxx
- couchbase/phrase_query.hxx
- couchbase/search_geo_distance_units.hxx
- couchbase/search_row_location.hxx
- couchbase/search_sort_geo_distance.hxx
- test/test_unit_search.cxx
Changes: 
- Add implementation for doc_id_query
- Add geo distance sorting
- Completed type of search_row_location
> CXXCBC-408 Search Public API Issues

- CMakeLists.txt
- core/impl/cluster.cxx
- core/impl/scope.cxx
- core/impl/search.cxx
- core/impl/search.hxx
- core/impl/search_request.cxx
- core/impl/vector_query.cxx
- core/impl/vector_search.cxx
- core/meta/features.hxx
- core/operations/document_search.cxx
- core/operations/document_search.hxx
- core/vector_query_combination.hxx
- couchbase/cluster.hxx
- couchbase/scope.hxx
- couchbase/search_request.hxx
- couchbase/vector_query.hxx
- couchbase/vector_search.hxx
- couchbase/vector_search_options.hxx
- test/test_unit_search.cxx
Changes:
- Added new cluster/scope.search() API
- New public search_request object
- Support for vector queries
> CXXCBC-434 Support for Vector Search

- core/impl/collection.cxx
- core/operations/document_lookup_in_all_replicas.hxx
- core/operations/document_lookup_in_any_replica.hxx
Changes:
- Wrapped LookupInReplica operations in an open_bucket, so that it fetches the bucket capabilities
> CXXCBC-479 LookupInReplica returning FeatureNotAvailable

- core/impl/bucket.cxx
- core/impl/cluster.cxx
- core/impl/error_context.cxx
- couchbase/bucket.hxx
- couchbase/cluster.hxx
- couchbase/cluster_options.hxx
- couchbase/diagnostics_options.hxx
- couchbase/error_context.hxx
- couchbase/fmt/error.hxx
- couchbase/ping_options.hxx
- examples/async_game_server.cxx
- examples/bulk_base_api.cxx
- examples/bulk_transactional_api.cxx
- examples/bulk_transactional_get_replace.cxx
- examples/distributed_mutex.cxx
- examples/game_server.cxx
- examples/minimal.cxx
- test/test_integration_connect.cxx
- test/test_integration_diagnostics.cxx
- test/test_integration_examples.cxx
- test/test_integration_management.cxx
- test/test_transaction_examples.cxx
- test/test_transaction_public_blocking_api.cxx
- test/utils/wait_until.cxx
- tools/analytics.cxx
- tools/beam.cxx
- tools/get.cxx
- tools/pillowfight.cxx
- tools/query.cxx
Changes
---------
- Updated connect, ping and diagnostics to return couchbase::error
> CXXCBC-508 Change connect, ping, diagnostics to use couchbase::error

- core/impl/vector_query.cxx
- core/meta/features.hxx
- couchbase/search_request.hxx
- couchbase/vector_query.hxx
- couchbase/vector_search.hxx
- test/test_unit_search.cxx
Changes
- Added support for base64 encoded vector query
- Bumped stability up to uncommitted
> CXXCBC-514 Support for base64 encoded vector types

- .github/workflows/windows.yml
- bin/build-tests.rb
- core/impl/configuration_profiles_registry.cxx
Attempt to diagnose and fix crash on Windows 2022 runner
> fix windows build

- core/columnar/query_component.cxx
This means that raw will override any other options already set
> CXXCBC-604: Columnar - apply raw options last

- core/operations/management/bucket_describe.cxx
- core/operations/management/bucket_drop.cxx
- core/operations/management/bucket_flush.cxx
- core/operations/management/bucket_get.cxx
- core/operations/management/bucket_update.cxx
- core/operations/management/collection_create.cxx
- core/operations/management/collection_drop.cxx
- core/operations/management/collection_update.cxx
- core/operations/management/group_upsert.cxx
- core/operations/management/scope_create.cxx
- core/operations/management/scope_drop.cxx
- core/operations/management/scope_get_all.cxx
- core/operations/management/search_index_analyze_document.cxx
- core/operations/management/search_index_control_ingest.cxx
- core/operations/management/search_index_control_plan_freeze.cxx
- core/operations/management/search_index_control_query.cxx
- core/operations/management/search_index_drop.cxx
- core/operations/management/search_index_get.cxx
- core/operations/management/search_index_get_all.cxx
- core/operations/management/search_index_get_documents_count.cxx
- core/operations/management/search_index_upsert.cxx
- core/operations/management/view_index_drop.cxx
- core/operations/management/view_index_get.cxx
- core/operations/management/view_index_get_all.cxx
- core/operations/management/view_index_upsert.cxx
- test/test_integration_management.cxx
Changes
---------
- Ensured bucket, scope & collections are properly encoded in URIs
> CXXCBC-311: SDKs must encode URIs

- .valgrind_suppressions.txt
- cmake/Packaging.cmake
- cmake/Testing.cmake
- cmake/couchbase-cxx-client.spec.in
- core/origin.cxx
> Update list of RPM-based platforms

- core/columnar/query_component.cxx
- test/test_integration_columnar_query.cxx
We have client-side timeouts both for the overall query and for each individual HTTP operation, and it appears possible that the individual HTTP timeout gets triggered before the overall query one and we lose all the error context retry information (last errors, number of retry attempts).
We should handle a timeout error code coming from the HTTP component, and report the same retry fields in the error context that we would otherwise do.
> CXXCBC-616: Columnar - report retry information when receiving a timeout from the HTTP component

- core/operations/document_analytics.cxx
"requestID", "clientContextID" and "metrics" might be missing.
For example, the following payload might be sent with status 503:
{
"errors": [
{
"code": 23000,
"msg": "Analytics Service is temporarily unavailable"
}
],
"status": "fatal"
}
> CXXCBC-632: Do not assume Analytics will always send meta fields in response

- core/operations/management/user_upsert.cxx
Changes:
- URI encode role location in user_upsert
> URI encode user_upsert

- core/io/dns_client.cxx
* catch `asio::error::operation_aborted` in every handler, and return immediately giving chance to deadline_ handler to report timeout error code
* make sure that UDP round will always fallback to TCP in case of UDP timeout.
> CXXCBC-633: ensure DNS-SRV resolver reports timeouts

- .gitignore
- core/origin.cxx
Changes
=======
* Update origin to_json() to include server_group option
* Change .ignore to ignore all jetbrains things (.idea)
> Minor improvements

- core/impl/cluster.cxx
> [backport] CXXCBC-661: Reconnect cluster object on fork

- test/test_integration_query.cxx
There have been failures on CI because of different amounts of whitespace in encoded rows. Since whitespace doesn't matter, it would be more robust to decode rows and then compare them with the expected.
> CXXCBC-673: Update query integration tests to compare decoded rows

- core/transactions/transactions.cxx
As part of the GetMulti changes, logic was added that converts the Public API TOF error, to a core exception and throws it. As we lose some of the context in the Public API, this was being done with the FAIL_OTHER error class. This caused many FIT failures, as for some error classes we expect different behaviour, like retries.
It’s not necessary to raise the TOF exceptions if returned from the lambda, as the core must always cache TOF errors internally with the full context around the error and the correct error class.
> CXXCBC-688: Don't convert Public API TOF from lambda to Core API's TOF, rely on internal state

- .github/workflows/columnar.yml
- .github/workflows/linters.yml
- .github/workflows/sanitizers.yml
- .github/workflows/tests.yml
- .github/workflows/windows.yml
> github actions: update trigger rules

- core/operations/management/search_index_get_all.cxx
> [backport] CXXCBC-693: Fix clang-tidy else-after-return error

- core/cluster.cxx
- core/topology/capabilities.cxx
- core/topology/capabilities.hxx
- core/topology/configuration.hxx
- core/topology/configuration_json.hxx
Changes:
- Updated config & cluster capability to check `prod` for `analytics`
> CXXCBC-692: Update prodName to prod for analytics capability check
